module fortnum_special_legendre
    ! Ferrers associated Legendre functions P_l^m(x), -1 <= x <= 1.
    !
    ! The Condon-Shortley phase is included. Negative orders follow
    ! P_l^(-m) = (-1)^m (l-m)!/(l+m)! P_l^m (DLMF 14.9.3).
    ! Degree recurrence and derivative coefficients are generated by fortsym
    ! from DLMF 14.10.3 and 14.10.5. Derivatives are defined for -1 < x < 1.
    use, intrinsic :: ieee_arithmetic, only: ieee_quiet_nan, ieee_value
    use fortnum_kinds, only: dp
    use fortnum_legendre_recurrence_kernel, only: &
        legendre_recurrence_kernel
    implicit none
    private

    public :: legendre_p, legendre_p_derivative

contains

    elemental function legendre_p(degree, order, x) result(value)
        integer, intent(in) :: degree, order
        real(dp), intent(in) :: x
        real(dp) :: value
        real(dp) :: derivative

        call evaluate_legendre(degree, order, x, value, derivative)
    end function legendre_p

    elemental function legendre_p_derivative(degree, order, x) result(value)
        integer, intent(in) :: degree, order
        real(dp), intent(in) :: x
        real(dp) :: value
        real(dp) :: function_value

        call evaluate_legendre(degree, order, x, function_value, value)
    end function legendre_p_derivative

    pure elemental subroutine evaluate_legendre( &
            degree, order, x, value, derivative)
        integer, intent(in) :: degree, order
        real(dp), intent(in) :: x
        real(dp), intent(out) :: value, derivative
        integer :: absolute_order, current_degree
        real(dp) :: previous, current, next, unused_derivative, factor

        if (degree < 0 .or. abs(order) > degree) then
            value = 0.0_dp
            derivative = 0.0_dp
            return
        end if
        if (abs(x) > 1.0_dp) then
            value = ieee_value(x, ieee_quiet_nan)
            derivative = value
            return
        end if

        absolute_order = abs(order)
        current = diagonal_seed(absolute_order, x)
        previous = 0.0_dp
        current_degree = absolute_order

        if (degree > absolute_order) then
            next = x*real(2*absolute_order + 1, dp)*current
            previous = current
            current = next
            current_degree = absolute_order + 1
        end if
        do while (current_degree < degree)
            call legendre_recurrence_kernel( &
                real(current_degree, dp), real(absolute_order, dp), x, &
                previous, current, next, unused_derivative)
            previous = current
            current = next
            current_degree = current_degree + 1
        end do

        call legendre_recurrence_kernel( &
            real(degree, dp), real(absolute_order, dp), x, &
            previous, current, next, derivative)
        factor = negative_order_factor(degree, order)
        value = factor*current
        derivative = factor*derivative
    end subroutine evaluate_legendre

    pure elemental function diagonal_seed(order, x) result(value)
        integer, intent(in) :: order
        real(dp), intent(in) :: x
        real(dp) :: value
        integer :: k

        value = 1.0_dp
        do k = 1, order
            value = -value*real(2*k - 1, dp)* &
                sqrt(max(0.0_dp, 1.0_dp - x*x))
        end do
    end function diagonal_seed

    pure elemental function negative_order_factor(degree, order) result(factor)
        integer, intent(in) :: degree, order
        real(dp) :: factor
        integer :: k, positive_order

        factor = 1.0_dp
        if (order >= 0) return
        positive_order = -order
        if (mod(positive_order, 2) == 1) factor = -factor
        do k = degree - positive_order + 1, degree + positive_order
            factor = factor/real(k, dp)
        end do
    end function negative_order_factor

end module fortnum_special_legendre
