module fortnum_special_toroidal
    ! Hobson-normalized toroidal functions P_(n-1/2)^m and Q_(n-1/2)^m.
    !
    ! This initial numerical region targets n,m >= 0 and x > 1 at ordinary
    ! torus aspect ratios. DLMF 14.3.7 supplies Q, while a Pfaff-transformed
    ! DLMF 14.3.6 supplies the P seed. Associated orders follow DLMF 14.10.6.
    ! The 2F1 term and order-recurrence kernels are generated by fortsym.
    use, intrinsic :: ieee_arithmetic, only: ieee_quiet_nan, ieee_value
    use fortnum_kinds, only: dp
    use fortnum_hypergeom_2f1_term_kernel, only: &
        hypergeom_2f1_term_kernel
    use fortnum_legendre_recurrence_kernel, only: &
        legendre_recurrence_kernel
    use fortnum_toroidal_order_kernel, only: toroidal_order_kernel
    implicit none
    private

    public :: toroidal_p, toroidal_q
    public :: toroidal_p_derivative, toroidal_q_derivative
    public :: toroidal_p_second_derivative, toroidal_q_second_derivative

    integer, parameter :: max_series_terms = 100000

contains

    elemental function toroidal_p(degree_index, order, x) result(value)
        integer, intent(in) :: degree_index, order
        real(dp), intent(in) :: x
        real(dp) :: value

        if (.not. valid_arguments(degree_index, order, x)) then
            value = ieee_value(x, ieee_quiet_nan)
            return
        end if
        value = associated_p(real(degree_index, dp) - 0.5_dp, order, x)
    end function toroidal_p

    elemental function toroidal_q(degree_index, order, x) result(value)
        integer, intent(in) :: degree_index, order
        real(dp), intent(in) :: x
        real(dp) :: value

        if (.not. valid_arguments(degree_index, order, x)) then
            value = ieee_value(x, ieee_quiet_nan)
            return
        end if
        value = associated_q(real(degree_index, dp) - 0.5_dp, order, x)
    end function toroidal_q

    elemental function toroidal_p_derivative( &
            degree_index, order, x) result(value)
        integer, intent(in) :: degree_index, order
        real(dp), intent(in) :: x
        real(dp) :: value

        value = associated_derivative( &
            degree_index, order, x, .true.)
    end function toroidal_p_derivative

    elemental function toroidal_q_derivative( &
            degree_index, order, x) result(value)
        integer, intent(in) :: degree_index, order
        real(dp), intent(in) :: x
        real(dp) :: value

        value = associated_derivative( &
            degree_index, order, x, .false.)
    end function toroidal_q_derivative

    elemental function toroidal_p_second_derivative( &
            degree_index, order, x) result(value)
        !! Second x derivative from the associated Legendre ODE.
        integer, intent(in) :: degree_index, order
        real(dp), intent(in) :: x
        real(dp) :: value, function_value, first_derivative
        real(dp) :: degree, denominator, order_squared

        if (.not. valid_arguments(degree_index, order, x)) then
            value = ieee_value(x, ieee_quiet_nan)
            return
        end if
        degree = real(degree_index, dp) - 0.5_dp
        function_value = associated_p(degree, order, x)
        first_derivative = associated_derivative( &
            degree_index, order, x, .true.)
        denominator = 1.0_dp - x*x
        order_squared = real(order*order, dp)
        value = (2.0_dp*x*first_derivative - &
            (degree*(degree + 1.0_dp) - order_squared/denominator)* &
            function_value)/denominator
    end function toroidal_p_second_derivative

    elemental function toroidal_q_second_derivative( &
            degree_index, order, x) result(value)
        !! Second x derivative from the associated Legendre ODE.
        integer, intent(in) :: degree_index, order
        real(dp), intent(in) :: x
        real(dp) :: value, function_value, first_derivative
        real(dp) :: degree, denominator, order_squared

        if (.not. valid_arguments(degree_index, order, x)) then
            value = ieee_value(x, ieee_quiet_nan)
            return
        end if
        degree = real(degree_index, dp) - 0.5_dp
        function_value = associated_q(degree, order, x)
        first_derivative = associated_derivative( &
            degree_index, order, x, .false.)
        denominator = 1.0_dp - x*x
        order_squared = real(order*order, dp)
        value = (2.0_dp*x*first_derivative - &
            (degree*(degree + 1.0_dp) - order_squared/denominator)* &
            function_value)/denominator
    end function toroidal_q_second_derivative

    pure elemental function associated_derivative( &
            degree_index, order, x, first_kind) result(value)
        integer, intent(in) :: degree_index, order
        real(dp), intent(in) :: x
        logical, intent(in) :: first_kind
        real(dp) :: value
        real(dp) :: degree, current, previous, unused_next

        if (.not. valid_arguments(degree_index, order, x)) then
            value = ieee_value(x, ieee_quiet_nan)
            return
        end if
        degree = real(degree_index, dp) - 0.5_dp
        if (first_kind) then
            current = associated_p(degree, order, x)
            previous = associated_p(degree - 1.0_dp, order, x)
        else
            current = associated_q(degree, order, x)
            previous = associated_q(degree - 1.0_dp, order, x)
        end if
        call legendre_recurrence_kernel( &
            degree, real(order, dp), x, previous, current, &
            unused_next, value)
    end function associated_derivative

    pure elemental function associated_p(degree, order, x) result(value)
        real(dp), intent(in) :: degree, x
        integer, intent(in) :: order
        real(dp) :: value
        real(dp) :: current, following, previous, unused_derivative
        integer :: degree_index, current_degree

        degree_index = nint(degree + 0.5_dp)
        if (degree_index < 2 .or. abs( &
            degree - (real(degree_index, dp) - 0.5_dp)) > 1.0e-12_dp) then
            value = associated_p_direct(degree, order, x)
            return
        end if

        previous = associated_p_direct(-0.5_dp, order, x)
        current = associated_p_direct(0.5_dp, order, x)
        do current_degree = 1, degree_index - 1
            call legendre_recurrence_kernel( &
                real(current_degree, dp) - 0.5_dp, real(order, dp), x, &
                previous, current, following, unused_derivative)
            previous = current
            current = following
        end do
        value = current
    end function associated_p

    pure elemental function associated_p_direct( &
            degree, order, x) result(value)
        real(dp), intent(in) :: degree, x
        integer, intent(in) :: order
        real(dp) :: value
        real(dp) :: p_zero, p_one, following, previous_degree
        real(dp) :: unused_next, derivative
        integer :: current_order

        p_zero = unassociated_p(degree, x)
        if (order == 0) then
            value = p_zero
            return
        end if

        previous_degree = unassociated_p(degree - 1.0_dp, x)
        call legendre_recurrence_kernel( &
            degree, 0.0_dp, x, previous_degree, p_zero, &
            unused_next, derivative)
        p_one = sqrt(x*x - 1.0_dp)*derivative
        if (order == 1) then
            value = p_one
            return
        end if

        do current_order = 0, order - 2
            call toroidal_order_kernel( &
                degree, real(current_order, dp), x, &
                p_zero, p_one, following)
            p_zero = p_one
            p_one = following
        end do
        value = p_one
    end function associated_p_direct

    pure elemental function unassociated_p(degree, x) result(value)
        real(dp), intent(in) :: degree, x
        real(dp) :: value
        real(dp) :: argument

        argument = (x - 1.0_dp)/(x + 1.0_dp)
        value = ((x + 1.0_dp)/2.0_dp)**degree* &
            hypergeom_2f1(-degree, -degree, 1.0_dp, argument)
    end function unassociated_p

    pure elemental function associated_q(degree, order, x) result(value)
        real(dp), intent(in) :: degree, x
        integer, intent(in) :: order
        real(dp) :: value
        integer :: degree_index

        degree_index = nint(degree + 0.5_dp)
        if (degree_index < 2 .or. x < 1.01_dp .or. abs( &
            degree - (real(degree_index, dp) - 0.5_dp)) > 1.0e-12_dp) then
            value = associated_q_direct(degree, order, x)
            return
        end if
        value = associated_q_miller(degree_index, order, x)
    end function associated_q

    pure elemental function associated_q_direct( &
            degree, order, x) result(value)
        real(dp), intent(in) :: degree, x
        integer, intent(in) :: order
        real(dp) :: value
        real(dp) :: q_zero, q_one, following, derivative
        integer :: current_order

        q_zero = unassociated_q(degree, x)
        if (order == 0) then
            value = q_zero
            return
        end if

        ! Generate the associated order from the analytical derivative of the
        ! zero-order branch.  This avoids cancellation between Q_nu and
        ! Q_(nu+1) in the near-cut region and uses the same DLMF 14.10.6
        ! recurrence as the generated P branch for the remaining orders.
        call unassociated_q_with_derivative(degree, x, q_zero, derivative)
        q_one = sqrt(x*x - 1.0_dp)*derivative
        if (order == 1) then
            value = q_one
            return
        end if
        do current_order = 0, order - 2
            call toroidal_order_kernel( &
                degree, real(current_order, dp), x, q_zero, q_one, following)
            q_zero = q_one
            q_one = following
        end do
        value = q_one
    end function associated_q_direct

    pure elemental function associated_q_miller( &
            degree_index, order, x) result(value)
        integer, intent(in) :: degree_index, order
        real(dp), intent(in) :: x
        real(dp) :: value
        real(dp) :: current, following, previous, normalization
        real(dp) :: scale, target_sequence, seed_sequence
        integer :: current_degree, top_degree

        ! Q is the recessive solution of the degree recurrence.  Forward
        ! recurrence therefore becomes unstable at larger toroidal degree;
        ! Miller's backward recurrence keeps the recessive branch and uses
        ! the independently evaluated degree -1/2 value for normalization.
        top_degree = degree_index + max(128, 4*order + 32)
        following = 0.0_dp
        current = 1.0_dp
        target_sequence = 0.0_dp
        seed_sequence = 0.0_dp
        do current_degree = top_degree, 1, -1
            previous = ((2.0_dp*(real(current_degree, dp) - 0.5_dp) + 1.0_dp)* &
                x*current - (real(current_degree, dp) - 0.5_dp - &
                real(order, dp) + 1.0_dp)*following)/ &
                (real(current_degree, dp) - 0.5_dp + real(order, dp))
            scale = max(abs(previous), abs(current), abs(following))
            if (scale > 1.0e100_dp) then
                previous = previous*1.0e-100_dp
                current = current*1.0e-100_dp
                following = following*1.0e-100_dp
            end if
            following = current
            current = previous
            if (current_degree - 1 == degree_index) &
                target_sequence = current
            if (current_degree - 1 == 0) seed_sequence = current
        end do
        normalization = associated_q_direct(-0.5_dp, order, x)/seed_sequence
        value = target_sequence*normalization
    end function associated_q_miller

    pure elemental function unassociated_q(degree, x) result(value)
        real(dp), intent(in) :: degree, x
        real(dp) :: value
        real(dp) :: unused_derivative

        call unassociated_q_with_derivative( &
            degree, x, value, unused_derivative)
    end function unassociated_q

    pure elemental subroutine unassociated_q_with_derivative( &
            degree, x, value, derivative)
        real(dp), intent(in) :: degree, x
        real(dp), intent(out) :: value, derivative
        real(dp) :: a, b, c, z, gap, pi, prefactor
        real(dp) :: hyper_value, hyper_derivative

        a = 0.5_dp*degree + 1.0_dp
        b = a - 0.5_dp
        c = degree + 1.5_dp
        ! Factor x^2-1 before subtracting one; this retains relative
        ! precision when x is only a few ulps above the torus cut.
        gap = ((x - 1.0_dp)*(x + 1.0_dp))/(x*x)
        z = 1.0_dp - gap
        if (z > 0.5_dp) then
            call zero_balanced_2f1_values( &
                a, b, z, gap, hyper_value, hyper_derivative)
        else
            hyper_value = hypergeom_2f1(a, b, c, z)
            hyper_derivative = a*b/c*hypergeom_2f1( &
                a + 1.0_dp, b + 1.0_dp, c + 1.0_dp, z)
        end if
        pi = acos(-1.0_dp)
        prefactor = sqrt(pi)*exp(log_gamma(degree + 1.0_dp) - &
            (degree + 1.0_dp)*log(2.0_dp) - &
            log_gamma(c))
        value = prefactor*exp(-(degree + 1.0_dp)*log(x))*hyper_value
        derivative = prefactor*exp(-(degree + 1.0_dp)*log(x))* &
            (-(degree + 1.0_dp)*hyper_value/x - &
            2.0_dp*hyper_derivative/(x*x*x))
    end subroutine unassociated_q_with_derivative

    pure elemental subroutine zero_balanced_2f1_values( &
            a, b, z, gap, value, derivative)
        ! DLMF 15.8.10, specialized to c=a+b.  Expanding in 1-z keeps the
        ! logarithmic Q branch convergent when x is close to the torus cut.
        real(dp), intent(in) :: a, b, z, gap
        real(dp), intent(out) :: value, derivative
        real(dp) :: coefficient, power, total, derivative_total
        real(dp) :: term, derivative_term, kappa, log_gap
        integer :: n

        coefficient = 1.0_dp
        power = 1.0_dp
        total = 0.0_dp
        derivative_total = 0.0_dp
        log_gap = log(gap)
        do n = 0, max_series_terms - 1
            kappa = 2.0_dp*digamma_positive(real(n + 1, dp)) - &
                digamma_positive(a + real(n, dp)) - &
                digamma_positive(b + real(n, dp))
            term = coefficient*power*(kappa - log_gap)
            derivative_term = coefficient*power*( &
                (1.0_dp - real(n, dp)*(kappa - log_gap))/ &
                gap)
            total = total + term
            derivative_total = derivative_total + derivative_term
            if (n > 2 .and. abs(term) <= epsilon(1.0_dp)*abs(total) .and. &
                abs(derivative_term) <= epsilon(1.0_dp)* &
                abs(derivative_total)) exit
            coefficient = coefficient*(a + real(n, dp))* &
                (b + real(n, dp))/real((n + 1)*(n + 1), dp)
            power = power*gap
        end do
        coefficient = exp(log_gamma(a + b) - log_gamma(a) - log_gamma(b))
        value = coefficient*total
        derivative = coefficient*derivative_total
    end subroutine zero_balanced_2f1_values

    pure function digamma_positive(argument) result(value)
        real(dp), intent(in) :: argument
        real(dp) :: value
        real(dp) :: x, inverse, inverse_squared

        value = 0.0_dp
        x = argument
        do while (x < 10.0_dp)
            value = value - 1.0_dp/x
            x = x + 1.0_dp
        end do
        inverse = 1.0_dp/x
        inverse_squared = inverse*inverse
        value = value + log(x) - 0.5_dp*inverse - inverse_squared*( &
            1.0_dp/12.0_dp - inverse_squared*(1.0_dp/120.0_dp - &
            inverse_squared*(1.0_dp/252.0_dp - inverse_squared*( &
            1.0_dp/240.0_dp - inverse_squared/132.0_dp))))
    end function digamma_positive

    pure elemental function hypergeom_2f1(a, b, c, z) result(value)
        real(dp), intent(in) :: a, b, c, z
        real(dp) :: value
        real(dp) :: term, next_term
        integer :: k

        value = 1.0_dp
        term = 1.0_dp
        do k = 0, max_series_terms - 1
            call hypergeom_2f1_term_kernel( &
                a, b, c, real(k, dp), z, term, next_term)
            value = value + next_term
            if (abs(next_term) <= epsilon(value)*abs(value)) return
            term = next_term
        end do
        value = ieee_value(value, ieee_quiet_nan)
    end function hypergeom_2f1

    pure elemental function valid_arguments( &
            degree_index, order, x) result(valid)
        integer, intent(in) :: degree_index, order
        real(dp), intent(in) :: x
        logical :: valid

        valid = degree_index >= 0 .and. order >= 0 .and. x > 1.0_dp
    end function valid_arguments

end module fortnum_special_toroidal
