module fortnum_special_legendre
    ! Ferrers associated Legendre functions P_l^m(x), -1 <= x <= 1, and
    ! ordinary Legendre functions of the second kind Q_l(x), x > 1.
    !
    ! The Condon-Shortley phase is included. Negative orders follow
    ! P_l^(-m) = (-1)^m (l-m)!/(l+m)! P_l^m (DLMF 14.9.3).
    ! Degree recurrence and derivative coefficients are generated by fortsym
    ! from DLMF 14.10.3 and 14.10.5. Derivatives are defined for -1 < x < 1.
    ! The Q seed and its recurrence follow DLMF 14.3.7 and 14.10.3; this
    ! real branch is intentionally restricted to x > 1. Q_l is the minimal
    ! solution of the degree recurrence there, so degrees with
    ! (l+1) acosh(x) > 1 use the backward ratio continued fraction anchored
    ! at Q_0 instead of the unstable upward recurrence.
    !
    ! legendre_p_normalized_table fills fully normalized functions
    ! Pbar_l^m(x) for 0 <= m <= l <= lmax with int_{-1}^{1} Pbar^2 dx = 1, by
    ! the diagonal seed and the stable upward degree recurrence of Holmes and
    ! Featherstone, J. Geodesy 76 (2002) 279-299, eqs. 11-13, carried in a
    ! (mantissa, binary exponent) form so that large orders neither underflow
    ! the seed nor overflow the recurrence.
    use, intrinsic :: ieee_arithmetic, only: ieee_quiet_nan, ieee_value
    use fortnum_kinds, only: dp
    use fortnum_legendre_recurrence_kernel, only: &
        legendre_recurrence_kernel
    implicit none
    private

    public :: legendre_p, legendre_p_derivative
    public :: legendre_p_second_derivative
    public :: legendre_q, legendre_q_derivative
    public :: legendre_q_second_derivative
    public :: legendre_p_normalized_table

contains

    elemental function legendre_p(degree, order, x) result(value)
        integer, intent(in) :: degree, order
        real(dp), intent(in) :: x
        real(dp) :: value
        real(dp) :: derivative

        call evaluate_legendre(degree, order, x, value, derivative)
    end function legendre_p

    elemental function legendre_p_derivative(degree, order, x) result(value)
        integer, intent(in) :: degree, order
        real(dp), intent(in) :: x
        real(dp) :: value
        real(dp) :: function_value

        call evaluate_legendre(degree, order, x, function_value, value)
    end function legendre_p_derivative

    elemental function legendre_p_second_derivative( &
            degree, order, x) result(value)
        !! Second x derivative from the associated Legendre ODE.
        integer, intent(in) :: degree, order
        real(dp), intent(in) :: x
        real(dp) :: value, function_value, first_derivative
        real(dp) :: denominator, order_squared

        if (degree < 0 .or. abs(order) > degree .or. abs(x) >= 1.0_dp) then
            value = ieee_value(x, ieee_quiet_nan)
            return
        end if
        call evaluate_legendre(degree, order, x, function_value, first_derivative)
        denominator = 1.0_dp - x*x
        order_squared = real(order*order, dp)
        value = (2.0_dp*x*first_derivative - &
            (real(degree*(degree + 1), dp) - order_squared/denominator)* &
            function_value)/denominator
    end function legendre_p_second_derivative

    elemental function legendre_q(degree, x) result(value)
        integer, intent(in) :: degree
        real(dp), intent(in) :: x
        real(dp) :: value
        real(dp) :: derivative

        call evaluate_legendre_q(degree, x, value, derivative)
    end function legendre_q

    elemental function legendre_q_derivative(degree, x) result(value)
        integer, intent(in) :: degree
        real(dp), intent(in) :: x
        real(dp) :: value
        real(dp) :: function_value

        call evaluate_legendre_q(degree, x, function_value, value)
    end function legendre_q_derivative

    elemental function legendre_q_second_derivative(degree, x) result(value)
        !! Second x derivative from the ordinary Legendre Q ODE.
        integer, intent(in) :: degree
        real(dp), intent(in) :: x
        real(dp) :: value, function_value, first_derivative

        if (degree < 0 .or. x <= 1.0_dp) then
            value = ieee_value(x, ieee_quiet_nan)
            return
        end if
        call evaluate_legendre_q(degree, x, function_value, first_derivative)
        value = (2.0_dp*x*first_derivative - &
            real(degree*(degree + 1), dp)*function_value)/ &
            (-(x - 1.0_dp)*(x + 1.0_dp))
    end function legendre_q_second_derivative

    pure elemental subroutine evaluate_legendre( &
            degree, order, x, value, derivative)
        integer, intent(in) :: degree, order
        real(dp), intent(in) :: x
        real(dp), intent(out) :: value, derivative
        integer :: absolute_order, current_degree
        real(dp) :: previous, current, next, unused_derivative, factor

        if (degree < 0 .or. abs(order) > degree) then
            value = 0.0_dp
            derivative = 0.0_dp
            return
        end if
        if (abs(x) > 1.0_dp) then
            value = ieee_value(x, ieee_quiet_nan)
            derivative = value
            return
        end if

        absolute_order = abs(order)
        current = diagonal_seed(absolute_order, x)
        previous = 0.0_dp
        current_degree = absolute_order

        if (degree > absolute_order) then
            next = x*real(2*absolute_order + 1, dp)*current
            previous = current
            current = next
            current_degree = absolute_order + 1
        end if
        do while (current_degree < degree)
            call legendre_recurrence_kernel( &
                real(current_degree, dp), real(absolute_order, dp), x, &
                previous, current, next, unused_derivative)
            previous = current
            current = next
            current_degree = current_degree + 1
        end do

        call legendre_recurrence_kernel( &
            real(degree, dp), real(absolute_order, dp), x, &
            previous, current, next, derivative)
        factor = negative_order_factor(degree, order)
        value = factor*current
        derivative = factor*derivative
    end subroutine evaluate_legendre

    pure elemental subroutine evaluate_legendre_q( &
            degree, x, value, derivative)
        integer, intent(in) :: degree
        real(dp), intent(in) :: x
        real(dp), intent(out) :: value, derivative
        integer :: current_degree
        real(dp) :: previous, current, next, unused_derivative, theta

        if (degree < 0 .or. x <= 1.0_dp) then
            value = ieee_value(x, ieee_quiet_nan)
            derivative = value
            return
        end if

        previous = legendre_q_zero(x)
        if (degree == 0) then
            value = previous
            derivative = -1.0_dp/((x - 1.0_dp)*(x + 1.0_dp))
            return
        end if

        ! Q_l is the minimal solution of the degree recurrence for x > 1;
        ! upward recurrence amplifies rounding by about P_l Q_0/(P_0 Q_l),
        ! which is modest only while (l+1) acosh(x) <= 1.
        theta = acosh(x)
        if (real(degree + 1, dp)*theta <= 1.0_dp) then
            current = x*previous - 1.0_dp
            current_degree = 1
            do while (current_degree < degree)
                call legendre_recurrence_kernel( &
                    real(current_degree, dp), 0.0_dp, x, previous, current, &
                    next, unused_derivative)
                previous = current
                current = next
                current_degree = current_degree + 1
            end do
        else
            call legendre_q_backward(degree, x, theta, previous, current)
        end if

        ! DLMF 14.10.5 with (x-1)(x+1) instead of x*x-1, which would lose
        ! eps/(x-1) relative accuracy next to the cut.
        derivative = real(degree, dp)*(x*current - previous)/ &
            ((x - 1.0_dp)*(x + 1.0_dp))
        value = current
    end subroutine evaluate_legendre_q

    pure elemental function legendre_q_zero(x) result(value)
        real(dp), intent(in) :: x
        real(dp) :: value

        ! atanh(1/x) avoids the log(1 + small) loss for large x; near the
        ! cut the explicit ratio keeps x - 1 exact.
        if (x < 2.0_dp) then
            value = 0.5_dp*log((x + 1.0_dp)/(x - 1.0_dp))
        else
            value = atanh(1.0_dp/x)
        end if
    end function legendre_q_zero

    pure elemental subroutine legendre_q_backward( &
            degree, x, theta, previous, current)
        !! Q_{l-1} and Q_l from the ratio continued fraction
        !! r_n = Q_n/Q_{n-1} = n/((2n+1)x - (n+1)r_{n+1}) (backward degree
        !! recurrence, Gautschi, SIAM Rev. 9 (1967) 24-82), anchored at Q_0.
        !! The tail r_{N+1} = 0 perturbs r_l by about exp(-2(N-l)acosh x),
        !! so N - l = 19/acosh(x) + 16 keeps that below 1e-16.
        integer, intent(in) :: degree
        real(dp), intent(in) :: x, theta
        real(dp), intent(inout) :: previous
        real(dp), intent(out) :: current
        real(dp) :: ratio, product, last_ratio
        integer :: n, start

        start = degree + 16 + ceiling(19.0_dp/theta)
        ratio = 0.0_dp
        do n = start, degree + 1, -1
            ratio = real(n, dp)/(real(2*n + 1, dp)*x - real(n + 1, dp)*ratio)
        end do
        product = 1.0_dp
        last_ratio = 1.0_dp
        do n = degree, 1, -1
            ratio = real(n, dp)/(real(2*n + 1, dp)*x - real(n + 1, dp)*ratio)
            if (n == degree) last_ratio = ratio
            product = product*ratio
        end do
        current = previous*product
        previous = current/last_ratio
    end subroutine legendre_q_backward

    pure elemental function diagonal_seed(order, x) result(value)
        integer, intent(in) :: order
        real(dp), intent(in) :: x
        real(dp) :: value
        integer :: k

        value = 1.0_dp
        do k = 1, order
            value = -value*real(2*k - 1, dp)* &
                sqrt(max(0.0_dp, 1.0_dp - x*x))
        end do
    end function diagonal_seed

    pure elemental function negative_order_factor(degree, order) result(factor)
        integer, intent(in) :: degree, order
        real(dp) :: factor
        integer :: k, positive_order

        factor = 1.0_dp
        if (order >= 0) return
        positive_order = -order
        if (mod(positive_order, 2) == 1) factor = -factor
        do k = degree - positive_order + 1, degree + positive_order
            factor = factor/real(k, dp)
        end do
    end function negative_order_factor

    ! Fully normalized associated Legendre table on -1 <= x <= 1:
    !   p(l, m) = Pbar_l^m(x) = s_m sqrt((2l+1)/2 (l-m)!/(l+m)!) P_l^m(x),
    ! for 0 <= l <= lmax, 0 <= m <= mmax, with p(l, m) = 0 for l < m.  P_l^m
    ! is the Ferrers function without the Condon-Shortley phase, and
    ! s_m = (-1)^m when condon_shortley is present and true, else 1.  Then
    ! int_{-1}^{1} Pbar_l^m Pbar_k^m dx = delta_lk, and with the phase,
    ! Y_l^m(theta, phi) = Pbar_l^m(cos theta) exp(i m phi)/sqrt(2 pi)
    ! is the DLMF 14.30 spherical harmonic returned by spherical_harmonic.
    ! The seed Pbar_m^m = sqrt(1/2) prod_{k=1}^{m} sqrt((2k+1)/(2k)) s^m,
    ! s = sqrt((1-x)(1+x)), and the degree recurrence
    !   Pbar_l^m = a_lm (x Pbar_{l-1}^m - Pbar_{l-2}^m/a_{l-1,m}),
    !   a_lm = sqrt((4l^2 - 1)/(l^2 - m^2)),
    ! run on scaled values with an integer binary exponent, so the table is
    ! finite and accurate for lmax of several thousand; only true values
    ! below the normal range are flushed.  x outside [-1, 1] yields NaN.
    ! The routine allocates nothing.  Derivative products are not provided.
    pure subroutine legendre_p_normalized_table(lmax, mmax, x, p, &
                                                condon_shortley)
        integer,  intent(in)  :: lmax, mmax
        real(dp), intent(in)  :: x
        real(dp), intent(out) :: p(0:lmax, 0:mmax)
        logical,  intent(in), optional :: condon_shortley

        integer,  parameter :: shift = 400
        real(dp), parameter :: big = 2.0_dp**shift, small = 2.0_dp**(-shift)
        real(dp) :: s, seed, a, a_prev, p_2, p_1, p_0, sign_m
        integer  :: l, m, seed_exp, e
        logical  :: phase

        if (lmax < 0 .or. mmax < 0) error stop &
            "fortnum_special_legendre: lmax and mmax must be >= 0"
        if (.not. (abs(x) <= 1.0_dp)) then
            p = ieee_value(x, ieee_quiet_nan)
            return
        end if
        phase = .false.
        if (present(condon_shortley)) phase = condon_shortley
        p = 0.0_dp
        s = sqrt((1.0_dp - x)*(1.0_dp + x))
        seed = sqrt(0.5_dp)
        seed_exp = 0
        sign_m = 1.0_dp
        do m = 0, min(lmax, mmax)
            if (m > 0) then
                seed = seed*(sqrt(real(2*m + 1, dp)/real(2*m, dp))*s)
                if (seed == 0.0_dp) exit
                if (seed < small) then
                    seed = seed*big
                    seed_exp = seed_exp - shift
                end if
                if (phase) sign_m = -sign_m
            end if
            ! Column m: scaled values p_* with true value p_* * 2**e.
            e = seed_exp
            p_1 = seed
            p(m, m) = sign_m*scale(p_1, e)
            if (m == lmax) cycle
            a_prev = sqrt(real(2*m + 3, dp))
            p_0 = a_prev*x*p_1
            p(m + 1, m) = sign_m*scale(p_0, e)
            do l = m + 2, lmax
                a = sqrt(real(2*l - 1, dp)*real(2*l + 1, dp) &
                         /(real(l - m, dp)*real(l + m, dp)))
                p_2 = p_1
                p_1 = p_0
                p_0 = a*(x*p_1 - p_2/a_prev)
                a_prev = a
                if (abs(p_0) > big) then
                    p_0 = p_0*small
                    p_1 = p_1*small
                    e = e + shift
                end if
                p(l, m) = sign_m*scale(p_0, e)
            end do
        end do
    end subroutine legendre_p_normalized_table

end module fortnum_special_legendre
