module fortnum_special_riccati_bessel
    ! Riccati-Bessel functions of integer degree for real x > 0:
    !   jhat_l(x) = x j_l(x),   yhat_l(x) = x y_l(x)   (DLMF 10.47.3, 10.49),
    ! so jhat_0 = sin x and yhat_0 = -cos x, with jhat_l ~ sin(x - l pi/2)
    ! and yhat_l ~ -cos(x - l pi/2) as x -> infinity.
    !
    ! Both satisfy f_{l+1} = ((2l+1)/x) f_l - f_{l-1} (DLMF 10.51.1). yhat
    ! is generated upward, which is stable for every l. jhat is the minimal
    ! solution for l > x, so for lmax > x it is generated by Miller's
    ! backward recurrence started where yhat_N/yhat_lmax exceeds 1e9 (the
    ! start error is about (yhat_lmax/yhat_N)^2), rescaled against overflow,
    ! and normalized by the Wronskian
    !   jhat_{l+1} yhat_l - jhat_l yhat_{l+1} = 1   (DLMF 10.50.3)
    ! at l = 0, which needs neither sin x nor cos x to be away from zero.
    ! For lmax <= x the upward recurrence is used for jhat as well.
    !
    ! Values that are not representable underflow to zero (jhat) or overflow
    ! to infinity (yhat). Invalid arguments (x <= 0, lmax < 0, or arrays
    ! shorter than lmax+1) fill the outputs with NaN.
    !
    ! Derivative candidate (ad.md sec. 1): analytical,
    !   f_l'(x) = f_{l-1}(x) - (l/x) f_l(x)  for l >= 1, from the same table.
    use, intrinsic :: iso_fortran_env, only: dp => real64
    use, intrinsic :: ieee_arithmetic, only: ieee_is_finite, ieee_quiet_nan, &
        ieee_value
    implicit none
    private

    public :: riccati_bessel

    real(dp), parameter :: big = 1.0e250_dp

contains

    pure subroutine riccati_bessel(lmax, x, jhat, yhat)
        integer, intent(in) :: lmax
        real(dp), intent(in) :: x
        real(dp), intent(out) :: jhat(0:), yhat(0:)
        integer :: l

        if (lmax < 0 .or. .not. x > 0.0_dp .or. size(jhat) < lmax + 1 .or. &
                size(yhat) < lmax + 1) then
            jhat = ieee_value(x, ieee_quiet_nan)
            yhat = jhat(0)
            return
        end if

        yhat(0) = -cos(x)
        jhat(0) = sin(x)
        if (lmax == 0) return
        yhat(1) = yhat(0)/x - jhat(0)
        jhat(1) = jhat(0)/x + yhat(0)
        do l = 1, lmax - 1
            yhat(l + 1) = real(2*l + 1, dp)/x*yhat(l) - yhat(l - 1)
        end do
        if (real(lmax, dp) <= x) then
            do l = 1, lmax - 1
                jhat(l + 1) = real(2*l + 1, dp)/x*jhat(l) - jhat(l - 1)
            end do
        else
            call jhat_miller(lmax, x, yhat, jhat)
        end if
    end subroutine riccati_bessel

    pure subroutine jhat_miller(lmax, x, yhat, jhat)
        integer, intent(in) :: lmax
        real(dp), intent(in) :: x, yhat(0:)
        real(dp), intent(inout) :: jhat(0:)
        real(dp) :: lower, upper, next, norm
        integer :: n, start

        start = miller_start(lmax, x, yhat)
        upper = 0.0_dp
        lower = 1.0_dp
        do n = start, 1, -1
            ! lower = f_n, upper = f_{n+1}; produce f_{n-1}
            if (n <= lmax) jhat(n) = lower
            next = real(2*n + 1, dp)/x*lower - upper
            upper = lower
            lower = next
            if (abs(lower) > big) then
                lower = lower/big
                upper = upper/big
                jhat(n:lmax) = jhat(n:lmax)/big
            end if
        end do
        jhat(0) = lower
        norm = 1.0_dp/(jhat(1)*yhat(0) - jhat(0)*yhat(1))
        jhat(0:lmax) = norm*jhat(0:lmax)
    end subroutine jhat_miller

    pure integer function miller_start(lmax, x, yhat) result(start)
        ! Continue yhat beyond lmax, scaled by max|yhat_{lmax-1:lmax}|, until it
        ! has grown by 1e9; past the turning point l ~ x growth is monotone.
        integer, intent(in) :: lmax
        real(dp), intent(in) :: x, yhat(0:)
        real(dp) :: previous, current, next, scale
        integer :: n

        start = lmax + 20
        scale = max(abs(yhat(lmax)), abs(yhat(lmax - 1)))
        if (.not. (ieee_is_finite(scale) .and. scale > 0.0_dp)) return
        previous = yhat(lmax - 1)/scale
        current = yhat(lmax)/scale
        n = lmax
        do while (abs(current) < 1.0e9_dp)
            next = real(2*n + 1, dp)/x*current - previous
            previous = current
            current = next
            n = n + 1
        end do
        start = n + 2
    end function miller_start

end module fortnum_special_riccati_bessel
