module fortnum_special_jacobi
    ! Classical Jacobi polynomials P_n^(alpha,beta)(x), alpha,beta > -1.
    !
    ! The three-term recurrence is generated by fortsym from DLMF 18.9.5.
    ! The derivative uses DLMF 18.9.15:
    ! d P_n^(a,b)/dx = (n+a+b+1) P_(n-1)^(a+1,b+1)/2.
    use, intrinsic :: ieee_arithmetic, only: ieee_quiet_nan, ieee_value
    use fortnum_generated_jacobi_recurrence, only: &
        jacobi_recurrence_kernel
    use fortnum_generated_scaled_jacobi_recurrence, only: &
        scaled_jacobi_recurrence_kernel
    use fortnum_generated_scaled_jacobi_gradient_recurrence, only: &
        scaled_jacobi_gradient_recurrence_kernel
    use fortnum_generated_scaled_jacobi_hessian_recurrence, only: &
        scaled_jacobi_hessian_recurrence_kernel
    use fortnum_kinds, only: dp
    implicit none
    private

    public :: jacobi_p, jacobi_p_derivative, scaled_jacobi_p
    public :: scaled_jacobi_p_gradient, scaled_jacobi_p_hessian
    public :: tetrahedron_koornwinder, triangle_dubiner
    public :: tetrahedron_koornwinder_gradient, triangle_dubiner_gradient
    public :: tetrahedron_koornwinder_hessian

contains

    elemental function jacobi_p(degree, alpha, beta, x) result(value)
        integer, intent(in) :: degree
        real(dp), intent(in) :: alpha, beta, x
        real(dp) :: value

        integer :: current_degree
        real(dp) :: current, next, previous

        if (degree < 0) then
            value = 0.0_dp
            return
        end if
        if (alpha <= -1.0_dp .or. beta <= -1.0_dp) then
            value = ieee_value(x, ieee_quiet_nan)
            return
        end if
        if (degree == 0) then
            value = 1.0_dp
            return
        end if

        previous = 1.0_dp
        current = 0.5_dp*(alpha - beta + (alpha + beta + 2.0_dp)*x)
        current_degree = 1
        do while (current_degree < degree)
            call jacobi_recurrence_kernel( &
                real(current_degree + 1, dp), alpha, beta, x, &
                previous, current, next)
            previous = current
            current = next
            current_degree = current_degree + 1
        end do
        value = current
    end function jacobi_p

    elemental function jacobi_p_derivative( &
            degree, alpha, beta, x) result(value)
        integer, intent(in) :: degree
        real(dp), intent(in) :: alpha, beta, x
        real(dp) :: value

        if (degree <= 0) then
            value = 0.0_dp
            return
        end if
        value = 0.5_dp*real(degree, dp) + 0.5_dp*(alpha + beta + 1.0_dp)
        value = value*jacobi_p(degree - 1, alpha + 1.0_dp, beta + 1.0_dp, x)
    end function jacobi_p_derivative

    elemental function scaled_jacobi_p( &
            degree, alpha, beta, numerator, scale) result(value)
        integer, intent(in) :: degree
        real(dp), intent(in) :: alpha, beta, numerator, scale
        real(dp) :: value

        integer :: current_degree
        real(dp) :: current, next, previous

        if (degree < 0) then
            value = 0.0_dp
            return
        end if
        if (alpha <= -1.0_dp .or. beta <= -1.0_dp) then
            value = ieee_value(numerator, ieee_quiet_nan)
            return
        end if
        if (degree == 0) then
            value = 1.0_dp
            return
        end if

        previous = 1.0_dp
        current = 0.5_dp*((alpha - beta)*scale + &
            (alpha + beta + 2.0_dp)*numerator)
        current_degree = 1
        do while (current_degree < degree)
            call scaled_jacobi_recurrence_kernel( &
                real(current_degree + 1, dp), alpha, beta, numerator, &
                scale, previous, current, next)
            previous = current
            current = next
            current_degree = current_degree + 1
        end do
        value = current
    end function scaled_jacobi_p

    pure subroutine scaled_jacobi_p_gradient( &
            degree, alpha, beta, numerator, scale, gradient)
        integer, intent(in) :: degree
        real(dp), intent(in) :: alpha, beta, numerator, scale
        real(dp), intent(out) :: gradient(2)

        integer :: current_degree
        real(dp) :: current, current_gradient(2), next, next_gradient(2)
        real(dp) :: previous, previous_gradient(2)

        gradient = 0.0_dp
        if (degree <= 0 .or. alpha <= -1.0_dp .or. beta <= -1.0_dp) return
        previous = 1.0_dp
        previous_gradient = 0.0_dp
        current = 0.5_dp*((alpha - beta)*scale + &
            (alpha + beta + 2.0_dp)*numerator)
        current_gradient = 0.5_dp*[alpha + beta + 2.0_dp, alpha - beta]
        current_degree = 1
        do while (current_degree < degree)
            call scaled_jacobi_gradient_recurrence_kernel( &
                real(current_degree + 1, dp), alpha, beta, numerator, &
                scale, previous, current, previous_gradient(1), &
                current_gradient(1), previous_gradient(2), &
                current_gradient(2), next, next_gradient(1), &
                next_gradient(2))
            previous = current
            previous_gradient = current_gradient
            current = next
            current_gradient = next_gradient
            current_degree = current_degree + 1
        end do
        gradient = current_gradient
    end subroutine scaled_jacobi_p_gradient

    pure subroutine scaled_jacobi_p_hessian( &
            degree, alpha, beta, numerator, scale, hessian)
        integer, intent(in) :: degree
        real(dp), intent(in) :: alpha, beta, numerator, scale
        real(dp), intent(out) :: hessian(2, 2)

        integer :: current_degree
        real(dp) :: current, current_gradient(2), current_hessian(2, 2)
        real(dp) :: next, next_gradient(2), next_hessian(2, 2)
        real(dp) :: previous, previous_gradient(2), previous_hessian(2, 2)

        hessian = 0.0_dp
        if (degree <= 1 .or. alpha <= -1.0_dp .or. beta <= -1.0_dp) return
        previous = 1.0_dp
        previous_gradient = 0.0_dp
        previous_hessian = 0.0_dp
        current = 0.5_dp*((alpha - beta)*scale + &
            (alpha + beta + 2.0_dp)*numerator)
        current_gradient = 0.5_dp*[alpha + beta + 2.0_dp, alpha - beta]
        current_hessian = 0.0_dp
        current_degree = 1
        do while (current_degree < degree)
            call scaled_jacobi_hessian_recurrence_kernel( &
                real(current_degree + 1, dp), alpha, beta, numerator, &
                scale, previous, current, previous_gradient(1), &
                current_gradient(1), previous_gradient(2), &
                current_gradient(2), previous_hessian(1, 1), &
                current_hessian(1, 1), previous_hessian(1, 2), &
                current_hessian(1, 2), previous_hessian(2, 2), &
                current_hessian(2, 2), next, next_gradient(1), &
                next_gradient(2), next_hessian(1, 1), &
                next_hessian(1, 2), next_hessian(2, 2))
            next_hessian(2, 1) = next_hessian(1, 2)
            previous = current
            previous_gradient = current_gradient
            previous_hessian = current_hessian
            current = next
            current_gradient = next_gradient
            current_hessian = next_hessian
            current_degree = current_degree + 1
        end do
        hessian = current_hessian
    end subroutine scaled_jacobi_p_hessian

    elemental function triangle_dubiner( &
            first_degree, second_degree, x, y) result(value)
        integer, intent(in) :: first_degree, second_degree
        real(dp), intent(in) :: x, y
        real(dp) :: value

        if (first_degree < 0 .or. second_degree < 0) then
            value = 0.0_dp
            return
        end if
        value = scaled_jacobi_p( &
            first_degree, 0.0_dp, 0.0_dp, 2.0_dp*x + y - 1.0_dp, &
            1.0_dp - y)
        value = value*jacobi_p( &
            second_degree, real(2*first_degree + 1, dp), 0.0_dp, &
            2.0_dp*y - 1.0_dp)
    end function triangle_dubiner

    pure subroutine triangle_dubiner_gradient( &
            first_degree, second_degree, x, y, gradient)
        integer, intent(in) :: first_degree, second_degree
        real(dp), intent(in) :: x, y
        real(dp), intent(out) :: gradient(2)

        real(dp) :: first, first_gradient(2), second, second_derivative

        gradient = 0.0_dp
        if (first_degree < 0 .or. second_degree < 0) return
        first = scaled_jacobi_p( &
            first_degree, 0.0_dp, 0.0_dp, 2.0_dp*x + y - 1.0_dp, &
            1.0_dp - y)
        call scaled_jacobi_p_gradient( &
            first_degree, 0.0_dp, 0.0_dp, 2.0_dp*x + y - 1.0_dp, &
            1.0_dp - y, first_gradient)
        second = jacobi_p( &
            second_degree, real(2*first_degree + 1, dp), 0.0_dp, &
            2.0_dp*y - 1.0_dp)
        second_derivative = 2.0_dp*jacobi_p_derivative( &
            second_degree, real(2*first_degree + 1, dp), 0.0_dp, &
            2.0_dp*y - 1.0_dp)
        gradient(1) = 2.0_dp*first_gradient(1)*second
        gradient(2) = (first_gradient(1) - first_gradient(2))*second + &
            first*second_derivative
    end subroutine triangle_dubiner_gradient

    elemental function tetrahedron_koornwinder( &
            first_degree, second_degree, third_degree, x, y, z) &
            result(value)
        integer, intent(in) :: first_degree, second_degree, third_degree
        real(dp), intent(in) :: x, y, z
        real(dp) :: value

        if (first_degree < 0 .or. second_degree < 0 .or. &
            third_degree < 0) then
            value = 0.0_dp
            return
        end if
        value = scaled_jacobi_p( &
            first_degree, 0.0_dp, 0.0_dp, &
            2.0_dp*x + y + z - 1.0_dp, 1.0_dp - y - z)
        value = value*scaled_jacobi_p( &
            second_degree, real(2*first_degree + 1, dp), 0.0_dp, &
            2.0_dp*y + z - 1.0_dp, 1.0_dp - z)
        value = value*jacobi_p( &
            third_degree, real(2*(first_degree + second_degree) + 2, dp), &
            0.0_dp, 2.0_dp*z - 1.0_dp)
    end function tetrahedron_koornwinder

    pure subroutine tetrahedron_koornwinder_gradient( &
            first_degree, second_degree, third_degree, x, y, z, gradient)
        integer, intent(in) :: first_degree, second_degree, third_degree
        real(dp), intent(in) :: x, y, z
        real(dp), intent(out) :: gradient(3)

        real(dp) :: first, first_gradient(2), second, second_gradient(2)
        real(dp) :: third, third_derivative

        gradient = 0.0_dp
        if (first_degree < 0 .or. second_degree < 0 .or. &
            third_degree < 0) return
        first = scaled_jacobi_p( &
            first_degree, 0.0_dp, 0.0_dp, &
            2.0_dp*x + y + z - 1.0_dp, 1.0_dp - y - z)
        call scaled_jacobi_p_gradient( &
            first_degree, 0.0_dp, 0.0_dp, &
            2.0_dp*x + y + z - 1.0_dp, 1.0_dp - y - z, first_gradient)
        second = scaled_jacobi_p( &
            second_degree, real(2*first_degree + 1, dp), 0.0_dp, &
            2.0_dp*y + z - 1.0_dp, 1.0_dp - z)
        call scaled_jacobi_p_gradient( &
            second_degree, real(2*first_degree + 1, dp), 0.0_dp, &
            2.0_dp*y + z - 1.0_dp, 1.0_dp - z, second_gradient)
        third = jacobi_p( &
            third_degree, real(2*(first_degree + second_degree) + 2, dp), &
            0.0_dp, 2.0_dp*z - 1.0_dp)
        third_derivative = 2.0_dp*jacobi_p_derivative( &
            third_degree, real(2*(first_degree + second_degree) + 2, dp), &
            0.0_dp, 2.0_dp*z - 1.0_dp)
        gradient(1) = 2.0_dp*first_gradient(1)*second*third
        gradient(2) = (first_gradient(1) - first_gradient(2))*second*third + &
            2.0_dp*first*second_gradient(1)*third
        gradient(3) = (first_gradient(1) - first_gradient(2))*second*third + &
            first*(second_gradient(1) - second_gradient(2))*third + &
            first*second*third_derivative
    end subroutine tetrahedron_koornwinder_gradient

    pure subroutine tetrahedron_koornwinder_hessian( &
            first_degree, second_degree, third_degree, x, y, z, hessian)
        integer, intent(in) :: first_degree, second_degree, third_degree
        real(dp), intent(in) :: x, y, z
        real(dp), intent(out) :: hessian(3, 3)

        real(dp) :: factor(3), factor_gradient(3, 3)
        real(dp) :: factor_hessian(3, 3, 3), local_gradient(2)
        real(dp) :: local_hessian(2, 2), map_numerator(3), map_scale(3)
        real(dp) :: alpha, third_first, third_second
        integer :: column, row

        hessian = 0.0_dp
        if (first_degree < 0 .or. second_degree < 0 .or. &
            third_degree < 0) return
        factor_hessian = 0.0_dp

        factor(1) = scaled_jacobi_p(first_degree, 0.0_dp, 0.0_dp, &
            2.0_dp*x + y + z - 1.0_dp, 1.0_dp - y - z)
        call scaled_jacobi_p_gradient(first_degree, 0.0_dp, 0.0_dp, &
            2.0_dp*x + y + z - 1.0_dp, 1.0_dp - y - z, local_gradient)
        call scaled_jacobi_p_hessian(first_degree, 0.0_dp, 0.0_dp, &
            2.0_dp*x + y + z - 1.0_dp, 1.0_dp - y - z, local_hessian)
        map_numerator = [2.0_dp, 1.0_dp, 1.0_dp]
        map_scale = [0.0_dp, -1.0_dp, -1.0_dp]
        call map_scaled_derivatives(local_gradient, local_hessian, &
            map_numerator, map_scale, factor_gradient(:, 1), &
            factor_hessian(:, :, 1))

        alpha = real(2*first_degree + 1, dp)
        factor(2) = scaled_jacobi_p(second_degree, alpha, 0.0_dp, &
            2.0_dp*y + z - 1.0_dp, 1.0_dp - z)
        call scaled_jacobi_p_gradient(second_degree, alpha, 0.0_dp, &
            2.0_dp*y + z - 1.0_dp, 1.0_dp - z, local_gradient)
        call scaled_jacobi_p_hessian(second_degree, alpha, 0.0_dp, &
            2.0_dp*y + z - 1.0_dp, 1.0_dp - z, local_hessian)
        map_numerator = [0.0_dp, 2.0_dp, 1.0_dp]
        map_scale = [0.0_dp, 0.0_dp, -1.0_dp]
        call map_scaled_derivatives(local_gradient, local_hessian, &
            map_numerator, map_scale, factor_gradient(:, 2), &
            factor_hessian(:, :, 2))

        alpha = real(2*(first_degree + second_degree) + 2, dp)
        factor(3) = jacobi_p(third_degree, alpha, 0.0_dp, 2.0_dp*z - 1.0_dp)
        factor_gradient(:, 3) = 0.0_dp
        factor_gradient(3, 3) = 2.0_dp*jacobi_p_derivative( &
            third_degree, alpha, 0.0_dp, 2.0_dp*z - 1.0_dp)
        third_first = 0.5_dp*real(third_degree, dp) + &
            0.5_dp*(alpha + 1.0_dp)
        third_second = 0.5_dp*real(third_degree - 1, dp) + &
            0.5_dp*(alpha + 3.0_dp)
        if (third_degree <= 1) then
            factor_hessian(3, 3, 3) = 0.0_dp
        else
            factor_hessian(3, 3, 3) = 4.0_dp*third_first*third_second* &
                jacobi_p(third_degree - 2, alpha + 2.0_dp, 2.0_dp, &
                2.0_dp*z - 1.0_dp)
        end if

        do column = 1, 3
            do row = 1, 3
                hessian(row, column) = &
                    factor_hessian(row, column, 1)*factor(2)*factor(3) + &
                    factor_hessian(row, column, 2)*factor(1)*factor(3) + &
                    factor_hessian(row, column, 3)*factor(1)*factor(2) + &
                    (factor_gradient(row, 1)*factor_gradient(column, 2) + &
                    factor_gradient(row, 2)*factor_gradient(column, 1))* &
                    factor(3) + &
                    (factor_gradient(row, 1)*factor_gradient(column, 3) + &
                    factor_gradient(row, 3)*factor_gradient(column, 1))* &
                    factor(2) + &
                    (factor_gradient(row, 2)*factor_gradient(column, 3) + &
                    factor_gradient(row, 3)*factor_gradient(column, 2))* &
                    factor(1)
            end do
        end do
    end subroutine tetrahedron_koornwinder_hessian

    pure subroutine map_scaled_derivatives( &
            local_gradient, local_hessian, map_numerator, map_scale, &
            gradient, hessian)
        real(dp), intent(in) :: local_gradient(2), local_hessian(2, 2)
        real(dp), intent(in) :: map_numerator(3), map_scale(3)
        real(dp), intent(out) :: gradient(3), hessian(3, 3)

        integer :: column, row

        gradient = map_numerator*local_gradient(1) + &
            map_scale*local_gradient(2)
        do column = 1, 3
            do row = 1, 3
                hessian(row, column) = &
                    map_numerator(row)*map_numerator(column)* &
                    local_hessian(1, 1) + &
                    (map_numerator(row)*map_scale(column) + &
                    map_scale(row)*map_numerator(column))* &
                    local_hessian(1, 2) + &
                    map_scale(row)*map_scale(column)*local_hessian(2, 2)
            end do
        end do
    end subroutine map_scaled_derivatives

end module fortnum_special_jacobi
