module fortnum_special_toroidal
    ! Hobson-normalized toroidal functions P_(n-1/2)^m and Q_(n-1/2)^m.
    !
    ! This initial numerical region targets n,m >= 0 and x > 1 at ordinary
    ! torus aspect ratios. DLMF 14.3.7 supplies Q, while a Pfaff-transformed
    ! DLMF 14.3.6 supplies the P seed. Associated orders follow DLMF 14.10.6.
    ! The 2F1 term and order-recurrence kernels are generated by fortsym.
    use, intrinsic :: ieee_arithmetic, only: ieee_quiet_nan, ieee_value
    use fortnum_kinds, only: dp
    use fortnum_hypergeom_2f1_term_kernel, only: &
        hypergeom_2f1_term_kernel
    use fortnum_legendre_recurrence_kernel, only: &
        legendre_recurrence_kernel
    use fortnum_toroidal_order_kernel, only: toroidal_order_kernel
    implicit none
    private

    public :: toroidal_p, toroidal_q
    public :: toroidal_p_derivative, toroidal_q_derivative

    integer, parameter :: max_series_terms = 100000

contains

    elemental function toroidal_p(degree_index, order, x) result(value)
        integer, intent(in) :: degree_index, order
        real(dp), intent(in) :: x
        real(dp) :: value

        if (.not. valid_arguments(degree_index, order, x)) then
            value = ieee_value(x, ieee_quiet_nan)
            return
        end if
        value = associated_p(real(degree_index, dp) - 0.5_dp, order, x)
    end function toroidal_p

    elemental function toroidal_q(degree_index, order, x) result(value)
        integer, intent(in) :: degree_index, order
        real(dp), intent(in) :: x
        real(dp) :: value

        if (.not. valid_arguments(degree_index, order, x)) then
            value = ieee_value(x, ieee_quiet_nan)
            return
        end if
        value = associated_q(real(degree_index, dp) - 0.5_dp, order, x)
    end function toroidal_q

    elemental function toroidal_p_derivative( &
            degree_index, order, x) result(value)
        integer, intent(in) :: degree_index, order
        real(dp), intent(in) :: x
        real(dp) :: value

        value = associated_derivative( &
            degree_index, order, x, .true.)
    end function toroidal_p_derivative

    elemental function toroidal_q_derivative( &
            degree_index, order, x) result(value)
        integer, intent(in) :: degree_index, order
        real(dp), intent(in) :: x
        real(dp) :: value

        value = associated_derivative( &
            degree_index, order, x, .false.)
    end function toroidal_q_derivative

    pure elemental function associated_derivative( &
            degree_index, order, x, first_kind) result(value)
        integer, intent(in) :: degree_index, order
        real(dp), intent(in) :: x
        logical, intent(in) :: first_kind
        real(dp) :: value
        real(dp) :: degree, current, previous, unused_next

        if (.not. valid_arguments(degree_index, order, x)) then
            value = ieee_value(x, ieee_quiet_nan)
            return
        end if
        degree = real(degree_index, dp) - 0.5_dp
        if (first_kind) then
            current = associated_p(degree, order, x)
            previous = associated_p(degree - 1.0_dp, order, x)
        else
            current = associated_q(degree, order, x)
            previous = associated_q(degree - 1.0_dp, order, x)
        end if
        call legendre_recurrence_kernel( &
            degree, real(order, dp), x, previous, current, &
            unused_next, value)
    end function associated_derivative

    pure elemental function associated_p(degree, order, x) result(value)
        real(dp), intent(in) :: degree, x
        integer, intent(in) :: order
        real(dp) :: value
        real(dp) :: p_zero, p_one, following, previous_degree
        real(dp) :: unused_next, derivative
        integer :: current_order

        p_zero = unassociated_p(degree, x)
        if (order == 0) then
            value = p_zero
            return
        end if

        previous_degree = unassociated_p(degree - 1.0_dp, x)
        call legendre_recurrence_kernel( &
            degree, 0.0_dp, x, previous_degree, p_zero, &
            unused_next, derivative)
        p_one = sqrt(x*x - 1.0_dp)*derivative
        if (order == 1) then
            value = p_one
            return
        end if

        do current_order = 0, order - 2
            call toroidal_order_kernel( &
                degree, real(current_order, dp), x, &
                p_zero, p_one, following)
            p_zero = p_one
            p_one = following
        end do
        value = p_one
    end function associated_p

    pure elemental function unassociated_p(degree, x) result(value)
        real(dp), intent(in) :: degree, x
        real(dp) :: value
        real(dp) :: argument

        argument = (x - 1.0_dp)/(x + 1.0_dp)
        value = ((x + 1.0_dp)/2.0_dp)**degree* &
            hypergeom_2f1(-degree, -degree, 1.0_dp, argument)
    end function unassociated_p

    pure elemental function associated_q(degree, order, x) result(value)
        real(dp), intent(in) :: degree, x
        integer, intent(in) :: order
        real(dp) :: value
        real(dp) :: a, b, c, pi, phase

        a = 0.5_dp*(degree + real(order, dp)) + 1.0_dp
        b = a - 0.5_dp
        c = degree + 1.5_dp
        pi = acos(-1.0_dp)
        phase = merge(-1.0_dp, 1.0_dp, mod(order, 2) == 1)
        value = phase*sqrt(pi)*gamma(degree + real(order, dp) + 1.0_dp)* &
            (x*x - 1.0_dp)**(0.5_dp*real(order, dp))* &
            hypergeom_2f1(a, b, c, 1.0_dp/(x*x))/ &
            (2.0_dp**(degree + 1.0_dp)* &
            x**(degree + real(order, dp) + 1.0_dp)*gamma(c))
    end function associated_q

    pure elemental function hypergeom_2f1(a, b, c, z) result(value)
        real(dp), intent(in) :: a, b, c, z
        real(dp) :: value
        real(dp) :: term, next_term
        integer :: k

        value = 1.0_dp
        term = 1.0_dp
        do k = 0, max_series_terms - 1
            call hypergeom_2f1_term_kernel( &
                a, b, c, real(k, dp), z, term, next_term)
            value = value + next_term
            if (abs(next_term) <= epsilon(value)*abs(value)) return
            term = next_term
        end do
        value = ieee_value(value, ieee_quiet_nan)
    end function hypergeom_2f1

    pure elemental function valid_arguments( &
            degree_index, order, x) result(valid)
        integer, intent(in) :: degree_index, order
        real(dp), intent(in) :: x
        logical :: valid

        valid = degree_index >= 0 .and. order >= 0 .and. x > 1.0_dp
    end function valid_arguments

end module fortnum_special_toroidal
