module fortnum_special_jacobi
    ! Classical Jacobi polynomials P_n^(alpha,beta)(x), alpha,beta > -1.
    !
    ! The three-term recurrence is generated by fortsym from DLMF 18.9.5.
    ! The derivative uses DLMF 18.9.15:
    ! d P_n^(a,b)/dx = (n+a+b+1) P_(n-1)^(a+1,b+1)/2.
    use, intrinsic :: ieee_arithmetic, only: ieee_quiet_nan, ieee_value
    use fortnum_generated_jacobi_recurrence, only: &
        jacobi_recurrence_kernel
    use fortnum_kinds, only: dp
    implicit none
    private

    public :: jacobi_p, jacobi_p_derivative

contains

    elemental function jacobi_p(degree, alpha, beta, x) result(value)
        integer, intent(in) :: degree
        real(dp), intent(in) :: alpha, beta, x
        real(dp) :: value

        integer :: current_degree
        real(dp) :: current, next, previous

        if (degree < 0) then
            value = 0.0_dp
            return
        end if
        if (alpha <= -1.0_dp .or. beta <= -1.0_dp) then
            value = ieee_value(x, ieee_quiet_nan)
            return
        end if
        if (degree == 0) then
            value = 1.0_dp
            return
        end if

        previous = 1.0_dp
        current = 0.5_dp*(alpha - beta + (alpha + beta + 2.0_dp)*x)
        current_degree = 1
        do while (current_degree < degree)
            call jacobi_recurrence_kernel( &
                real(current_degree + 1, dp), alpha, beta, x, &
                previous, current, next)
            previous = current
            current = next
            current_degree = current_degree + 1
        end do
        value = current
    end function jacobi_p

    elemental function jacobi_p_derivative( &
            degree, alpha, beta, x) result(value)
        integer, intent(in) :: degree
        real(dp), intent(in) :: alpha, beta, x
        real(dp) :: value

        if (degree <= 0) then
            value = 0.0_dp
            return
        end if
        value = 0.5_dp*real(degree, dp) + 0.5_dp*(alpha + beta + 1.0_dp)
        value = value*jacobi_p(degree - 1, alpha + 1.0_dp, beta + 1.0_dp, x)
    end function jacobi_p_derivative

end module fortnum_special_jacobi
