program test_fortnum_quadrature_oracle
    ! Oracle test for fortnum_quadrature: compares gauss_legendre nodes and
    ! weights against the reference table generated by
    ! numpy.polynomial.legendre.leggauss for n in {2,3,4,5,8,12,16,32}.
    !
    ! CSV layout: n,i,node,weight
    ! Node ordering: numpy returns nodes ascending; gauss_legendre also returns
    ! nodes ascending, so they are compared index-by-index.
    !
    ! Tolerance: 1e-14 absolute (< 10 ulps at float64); nodes near zero must
    ! also satisfy this.  The implementation is Newton iteration to ~4*eps,
    ! so agreement with numpy (which uses LAPACK dstev on the Jacobi matrix)
    ! to 14 significant digits is expected.
    use, intrinsic :: iso_fortran_env, only: dp => real64, error_unit
    use fortnum_quadrature, only: gauss_legendre
    implicit none

    character(len=4096) :: path
    integer             :: arglen, argstat, unit, ios
    character(len=512)  :: line

    ! Oracle values read from CSV.
    integer, parameter  :: max_rows = 200
    integer  :: csv_n(max_rows), csv_i(max_rows), nrows, row
    real(dp) :: csv_node(max_rows), csv_weight(max_rows)

    integer, parameter  :: n_list(8) = [2, 3, 4, 5, 8, 12, 16, 32]
    real(dp), parameter :: atol = 1.0e-14_dp
    real(dp), parameter :: rtol = 1.0e-14_dp

    integer  :: j, n, i, nfail
    real(dp) :: err_x, err_w

    ! Current rule arrays; max_n must cover the largest n in n_list.
    integer, parameter :: max_n = 32
    real(dp) :: x(max_n), w(max_n)

    call get_command_argument(1, path, arglen, argstat)
    if (argstat /= 0 .or. arglen == 0) then
        write (error_unit, "(a)") &
            "usage: test_fortnum_quadrature_oracle <gauss_legendre.csv>"
        stop 1
    end if

    ! Read CSV into arrays.
    open (newunit=unit, file=path(1:arglen), status="old", action="read", &
        iostat=ios)
    if (ios /= 0) then
        write (error_unit, "(a)") "cannot open: "//path(1:arglen)
        stop 1
    end if
    nrows = 0
    do
        read (unit, "(a)", iostat=ios) line
        if (ios /= 0) exit
        if (len_trim(line) == 0) cycle
        if (line(verify(line, " "):verify(line, " ")) == "#") cycle
        nrows = nrows + 1
        if (nrows > max_rows) then
            write (error_unit, "(a)") "oracle: too many rows"
            stop 1
        end if
        call replace_commas(line)
        read (line, *, iostat=ios) csv_n(nrows), csv_i(nrows), &
            csv_node(nrows), csv_weight(nrows)
        if (ios /= 0) then
            write (error_unit, "(a,i0)") "oracle: parse error at row ", nrows
            stop 1
        end if
    end do
    close (unit)

    nfail = 0

    do j = 1, size(n_list)
        n = n_list(j)
        call gauss_legendre(n, x(1:n), w(1:n))

        do row = 1, nrows
            if (csv_n(row) /= n) cycle
            i = csv_i(row)
            if (i < 1 .or. i > n) then
                write (error_unit, "(a,i0,a,i0)") "oracle: bad index i=", i, &
                    " for n=", n
                nfail = nfail + 1
                cycle
            end if

            err_x = abs(x(i) - csv_node(row))
            err_w = abs(w(i) - csv_weight(row))
            if (err_x > atol + rtol*abs(csv_node(row)) .or. &
                err_w > atol + rtol*abs(csv_weight(row))) then
                nfail = nfail + 1
                if (nfail == 1) then
                    write (error_unit, "(a)") &
                        "oracle FAIL: n,i  ours_node ref_node  ours_w ref_w"
                end if
                write (error_unit, "(2(i4,1x),4(es22.14,1x))") &
                    n, i, x(i), csv_node(row), w(i), csv_weight(row)
            end if
        end do
    end do

    if (nfail > 0) then
        write (error_unit, "(i0,a)") nfail, " oracle row(s) failed"
        stop 1
    end if

    write (*, "(a,i0,a)") "oracle passed: ", nrows, " rows verified"
    stop 0

contains

    subroutine replace_commas(buf)
        character(*), intent(inout) :: buf
        integer :: k
        do k = 1, len(buf)
            if (buf(k:k) == ",") buf(k:k) = " "
        end do
    end subroutine replace_commas

end program test_fortnum_quadrature_oracle
