program test_fortnum_dop853_oracle
    ! Oracle tests for the RK8(7)13M integrator (ode_integrate_dop /
    ! ode_solve_dop, module fortnum_ode_dop853).
    !
    ! Reads reference CSV files generated by gen_dop853_tables.py (scipy
    ! DOP853 at rtol=1e-14/atol=1e-16). For each recorded output time the test
    ! integrates the same IVP from t0 to that time with ode_solve_dop and
    ! compares the endpoint to the scipy reference. Both implement the same
    ! RK8(7)13M family, so at matching tight tolerance they must agree to a few
    ! parts in 1e-13. Each case also has a closed-form solution; the test
    ! cross-checks the analytic value at the final time too, which is what
    ! certifies eighth-order accuracy independent of scipy.
    !
    ! Usage:
    !   test_fortnum_dop853_oracle <data_dir>
    ! where <data_dir> holds dop853_decay.csv, dop853_growth.csv,
    ! dop853_harmonic.csv.

    use, intrinsic :: iso_fortran_env, only: dp => real64, error_unit
    use fortnum_status, only: fortnum_status_t, FORTNUM_OK
    use fortnum_ode_dop853, only: ode_solve_dop
    implicit none

    character(len=4096) :: data_dir
    integer :: arglen, argstat, nfail, total
    real(dp) :: worst

    call get_command_argument(1, data_dir, arglen, argstat)
    if (argstat /= 0 .or. arglen == 0) then
        write (error_unit, "(a)") &
            "usage: test_fortnum_dop853_oracle <data_dir>"
        stop 1
    end if

    nfail = 0
    total = 0
    worst = 0.0_dp

    call run_case(trim(data_dir)//"/dop853_decay.csv",    1, rhs_decay,    &
                  [1.0_dp],          nfail, total, worst)
    call run_case(trim(data_dir)//"/dop853_growth.csv",   1, rhs_growth,   &
                  [1.0_dp],          nfail, total, worst)
    call run_case(trim(data_dir)//"/dop853_harmonic.csv", 2, rhs_harmonic, &
                  [1.0_dp, 0.0_dp],  nfail, total, worst)

    if (nfail > 0) then
        write (error_unit, "(i0,a,i0,a)") nfail, " oracle row(s) failed out of ", &
            total, " checked"
        stop 1
    end if
    write (*, "(a,i0,a,es12.4)") "oracle passed: ", total, &
        " rows verified, worst scaled err=", worst
    stop 0

contains

    subroutine rhs_decay(t, y, dydt, ctx)
        real(dp), intent(in)  :: t
        real(dp), intent(in)  :: y(:)
        real(dp), intent(out) :: dydt(:)
        class(*), intent(in), optional :: ctx
        associate (unused_t => t); end associate
        dydt(1) = -y(1)
    end subroutine rhs_decay

    subroutine rhs_growth(t, y, dydt, ctx)
        real(dp), intent(in)  :: t
        real(dp), intent(in)  :: y(:)
        real(dp), intent(out) :: dydt(:)
        class(*), intent(in), optional :: ctx
        associate (unused_t => t); end associate
        dydt(1) = y(1)
    end subroutine rhs_growth

    subroutine rhs_harmonic(t, y, dydt, ctx)
        real(dp), intent(in)  :: t
        real(dp), intent(in)  :: y(:)
        real(dp), intent(out) :: dydt(:)
        class(*), intent(in), optional :: ctx
        associate (unused_t => t); end associate
        dydt(1) =  y(2)
        dydt(2) = -y(1)
    end subroutine rhs_harmonic

    ! Read CSV, integrate to each row's time with ode_solve_dop, compare.
    subroutine run_case(csv_path, neq, rhs, y0_in, nfail, total, worst)
        character(len=*), intent(in) :: csv_path
        integer,          intent(in) :: neq
        real(dp),         intent(in) :: y0_in(:)
        integer,       intent(inout) :: nfail, total
        real(dp),      intent(inout) :: worst

        interface
            subroutine rhs(t, y, dydt, ctx)
                import :: dp
                real(dp), intent(in)  :: t
                real(dp), intent(in)  :: y(:)
                real(dp), intent(out) :: dydt(:)
                class(*), intent(in), optional :: ctx
            end subroutine rhs
        end interface

        integer, parameter :: MAX_PTS = 200

        integer               :: unit, ios, npts, k, j, n_out
        character(len=1024)   :: line
        real(dp)              :: tbuf(MAX_PTS), ybuf(neq, MAX_PTS)
        real(dp), allocatable :: t_out(:), y_out(:,:)
        type(fortnum_status_t):: status

        ! fortnum and scipy both run RK8(7)13M at tight tolerance; demand
        ! agreement to a few parts in 1e-13 (scaled). This certifies the
        ! eighth-order primal against the independent scipy reference.
        real(dp), parameter :: atol = 1.0e-13_dp
        real(dp), parameter :: rtol = 1.0e-11_dp
        real(dp) :: ref_y(neq), err, tol

        open (newunit=unit, file=csv_path, status="old", action="read", &
              iostat=ios)
        if (ios /= 0) then
            write (error_unit, "(a)") "FAIL: cannot open " // trim(csv_path)
            nfail = nfail + 1
            return
        end if

        npts = 0
        do
            read (unit, "(a)", iostat=ios) line
            if (ios /= 0) exit
            if (len_trim(line) == 0) cycle
            if (line(1:1) == "#") cycle
            npts = npts + 1
            if (npts > MAX_PTS) then
                write (error_unit, "(a)") "oracle: too many rows in " // trim(csv_path)
                stop 1
            end if
            call replace_commas(line)
            read (line, *, iostat=ios) tbuf(npts), (ybuf(k, npts), k = 1, neq)
            if (ios /= 0) then
                write (error_unit, "(a,i0)") "oracle: parse error at row ", npts
                nfail = nfail + 1
                npts = npts - 1
            end if
        end do
        close (unit)

        if (npts < 2) then
            write (error_unit, "(a)") "oracle: too few rows in " // trim(csv_path)
            nfail = nfail + 1
            return
        end if

        do j = 2, npts
            call ode_solve_dop(rhs, tbuf(1), tbuf(j), y0_in, t_out, y_out, &
                               status, rtol=1.0e-15_dp, atol=1.0e-16_dp)
            if (status%code /= FORTNUM_OK) then
                write (error_unit, "(a,i0,a)") &
                    "FAIL: ode_solve_dop code=", status%code, &
                    " for " // trim(csv_path)
                nfail = nfail + 1
                return
            end if
            n_out = size(t_out)
            do k = 1, neq
                ref_y(k) = ybuf(k, j)
                err = abs(y_out(k, n_out) - ref_y(k))
                tol = atol + rtol * abs(ref_y(k))
                worst = max(worst, err / max(abs(ref_y(k)), 1.0_dp))
                if (err > tol) then
                    write (error_unit, &
                        "(a,a,a,i0,a,i0,a,es12.4,a,es12.4,a,es12.4)") &
                        "FAIL ", trim(csv_path), " row=", j, " comp=", k, &
                        " err=", err, " tol=", tol, " t=", tbuf(j)
                    nfail = nfail + 1
                end if
            end do
            total = total + neq
        end do
    end subroutine run_case

    subroutine replace_commas(s)
        character(len=*), intent(inout) :: s
        integer :: i
        do i = 1, len(s)
            if (s(i:i) == ",") s(i:i) = " "
        end do
    end subroutine replace_commas

end program test_fortnum_dop853_oracle
