program gen_dop853_tableau
    !> DOP853's twelve-stage tableau, derived rather than transcribed.
    !>
    !> fortnum_ode_dop853.f90 carried these coefficients as decimal literals
    !> copied from Hairer and Wanner's dop853.f. They are not rational -- the
    !> nodes are built from sqrt(6) -- so there was no exact form to check them
    !> against and nothing ever did.
    !>
    !> This states the four free nodes Dormand and Prince chose (Hairer,
    !> Norsett and Wanner, Solving Ordinary Differential Equations I, 2nd
    !> edition, p.185) and asks fortsym to solve the reduced system of section
    !> II.5 exactly in Q(sqrt 6). Every other coefficient is derived. The
    !> published decimals appear here only in the drift check that follows, as
    !> an oracle, never as an input.
    use fortsym_quadratic, only: quadratic_t, quad_rational, quad_to_real, &
        quad_text
    use fortsym_rk_reduced, only: rk_dp8_t, rk_dormand_prince_8, &
        RK_DP8_OK, RK_DP8_STAGES
    use fortnum_codegen_provenance, only: codegen_log, generated_path
    implicit none

    integer, parameter :: dp = kind(1.0d0)
    integer, parameter :: D = 6

    type(rk_dp8_t) :: tableau
    integer :: status, unit, ios, i, j
    logical :: ok
    character(:), allocatable :: path

    call rk_dormand_prince_8(rat("1/4"), rat("4/13"), rat("3/5"), rat("6/7"), &
                             tableau, status)
    if (status /= RK_DP8_OK) then
        error stop "DOP853: the reduced system did not solve exactly"
    end if
    call codegen_log("DOP853: reduced system solved exactly in Q(sqrt 6)")

    path = generated_path("fortnum_dop853_tableau.f90")
    open (newunit=unit, file=path, status="replace", action="write", iostat=ios)
    if (ios /= 0) error stop "cannot write "//path

    write (unit, "(a)") "! Generated by fortsym. Do not edit."
    write (unit, "(a)") "! Generator: gen_dop853_tableau"
    write (unit, "(a)") "! Generator revision: "//revision()
    write (unit, "(a)") "! Regenerate with: cd tools/codegen && fo exec "// &
        "gen_dop853_tableau"
    write (unit, "(a)") "!"
    write (unit, "(a)") "! Derived, not transcribed. The four free nodes"
    write (unit, "(a)") "! c7 = 1/4, c8 = 4/13, c10 = 3/5, c11 = 6/7 are the"
    write (unit, "(a)") "! values Dormand and Prince chose (Hairer, Norsett,"
    write (unit, "(a)") "! Wanner, Solving ODEs I, 2nd ed., p.185); every"
    write (unit, "(a)") "! other coefficient follows from the reduced system"
    write (unit, "(a)") "! of section II.5, solved exactly in Q(sqrt 6)."
    write (unit, "(a)") "!"
    write (unit, "(a)") "! The exact values are recorded beside each constant."
    write (unit, "(a)") "! They are not decimals of unknown provenance: each"
    write (unit, "(a)") "! is an element of Q(sqrt 6) and the rounding to a"
    write (unit, "(a)") "! double happens once, here."
    write (unit, "(a)") ""
    write (unit, "(a)") "module fortnum_dop853_tableau"
    write (unit, "(a)") "    use, intrinsic :: iso_fortran_env, only: dp => real64"
    write (unit, "(a)") "    implicit none"
    write (unit, "(a)") "    private"
    write (unit, "(a)") ""
    write (unit, "(a)") "    public :: dop853_c, dop853_b, dop853_a"
    write (unit, "(a)") ""
    write (unit, "(a,i0)") "    integer, parameter, public :: DOP853_STAGES = ", &
        RK_DP8_STAGES
    write (unit, "(a)") ""

    call emit_vector(unit, "dop853_c", tableau%c)
    call emit_vector(unit, "dop853_b", tableau%b)
    call emit_matrix(unit, "dop853_a", tableau%a)

    write (unit, "(a)") "end module fortnum_dop853_tableau"
    close (unit)
    call codegen_log("wrote "//path)

contains

    function rat(text) result(value)
        character(*), intent(in) :: text
        type(quadratic_t) :: value
        logical :: s

        value = quad_rational(text, D, s)
        if (.not. s) error stop "DOP853: bad free node "//text
    end function rat

    subroutine emit_vector(unit, name, values)
        integer, intent(in) :: unit
        character(*), intent(in) :: name
        type(quadratic_t), intent(in) :: values(:)
        integer :: k

        write (unit, "(a)") "    real(dp), parameter :: "//name// &
            "(DOP853_STAGES) = [ &"
        do k = 1, size(values)
            call emit_entry(unit, values(k), k == size(values), "        ")
        end do
        write (unit, "(a)") "        ]"
        write (unit, "(a)") ""
    end subroutine emit_vector

    subroutine emit_matrix(unit, name, values)
        integer, intent(in) :: unit
        character(*), intent(in) :: name
        type(quadratic_t), intent(in) :: values(:, :)
        integer :: r, c, n

        n = size(values, 1)
        write (unit, "(a)") "    !> a(i, j) in row-major reading order, so the"
        write (unit, "(a)") "    !> literal below matches the tableau layout."
        write (unit, "(a)") "    real(dp), parameter :: "//name// &
            "(DOP853_STAGES, DOP853_STAGES) = transpose(reshape([ &"
        do r = 1, n
            do c = 1, n
                call emit_entry(unit, values(r, c), r == n .and. c == n, &
                                "        ")
            end do
        end do
        write (unit, "(a)") "        ], [DOP853_STAGES, DOP853_STAGES]))"
        write (unit, "(a)") ""
    end subroutine emit_matrix

    !> One constant, with the exact field element it came from in a comment.
    subroutine emit_entry(unit, value, last, indent)
        integer, intent(in) :: unit
        type(quadratic_t), intent(in) :: value
        logical, intent(in) :: last
        character(*), intent(in) :: indent
        real(dp) :: rounded
        logical :: s
        character(len=40) :: text
        character(len=2) :: tail

        rounded = quad_to_real(value, s)
        if (.not. s) error stop "DOP853: coefficient is not representable"
        ! 17 significant digits round-trip an IEEE double, and the field must
        ! hold sign, digit, point, digits, E, exponent sign and three exponent
        ! digits: 25 characters for a negative value.
        write (text, "(es26.17e3)") rounded
        if (last) then
            tail = " "
        else
            tail = ", "
        end if
        write (unit, "(a)") indent//trim(adjustl(text))//"_dp"//trim(tail)// &
            "&  ! "//quad_text(value)
    end subroutine emit_entry

    function revision() result(text)
        character(:), allocatable :: text
        character(128) :: line
        integer :: u, stat

        open (newunit=u, file="fortsym-rk54.lock", status="old", &
              action="read", iostat=stat)
        if (stat /= 0) error stop "cannot read fortsym-rk54.lock"
        read (u, "(a)", iostat=stat) line
        close (u)
        if (stat /= 0) error stop "cannot parse fortsym-rk54.lock"
        text = "fortsym@"//trim(line)
    end function revision

end program gen_dop853_tableau
