program gen_rk54_cpu_tableau
    !> The Cash-Karp coefficients the CPU stepper uses, derived from the
    !> verified tableau rather than transcribed a second time.
    !>
    !> fortnum_ode_cash_karp.f90 used to declare this tableau itself, in
    !> parallel with the device kernels and with gen_rk54_device. Three copies
    !> of one method, none of them checked. This emits one module from the same
    !> tableau the device kernels come from, after the same order conditions.
    !>
    !> The embedded error weights are emitted pre-reduced. The stepper used to
    !> form them as (b5_1 - b4_1) and so on, which is correct but states the
    !> subtraction in the consumer; here b - bhat is derived once, in exact
    !> arithmetic, and rounded once.
    use fortsym_exact, only: exact_to_real
    use fortsym_rk, only: butcher_t, rk_from_rows, rk_is_consistent, &
        rk_attains_order, rk_error_weights, rk_is_fsal
    use fortsym_string, only: str_t, str, chars
    use fortnum_codegen_provenance, only: codegen_log, generated_path
    implicit none

    integer, parameter :: dp = kind(1.0d0)

    type(butcher_t) :: tableau
    type(str_t), allocatable :: error_weights(:)
    type(str_t), allocatable :: names(:), values(:)
    character(:), allocatable :: path
    integer :: unit, ios, i, j
    logical :: ok

    call build_cash_karp(tableau)
    call verify(tableau)

    error_weights = rk_error_weights(tableau, ok)
    if (.not. ok) error stop "Cash-Karp embedded weights are missing"

    path = generated_path("fortnum_rk54_ck_tableau.f90")
    open (newunit=unit, file=path, status="replace", action="write", &
          iostat=ios)
    if (ios /= 0) error stop "cannot write "//path

    allocate (names(0), values(0))
    do i = 2, tableau%stages
        call collect("ck_c"//digits(i), chars(tableau%c(i)))
    end do
    do i = 2, tableau%stages
        do j = 1, i - 1
            call collect("ck_a"//digits(i)//digits(j), chars(tableau%a(i, j)))
        end do
    end do
    do i = 1, tableau%stages
        if (chars(tableau%b(i)) == "0") cycle
        call collect("ck_b"//digits(i), chars(tableau%b(i)))
    end do
    do i = 1, tableau%stages
        if (chars(error_weights(i)) == "0") cycle
        call collect("ck_e"//digits(i), chars(error_weights(i)))
    end do

    write (unit, "(a)") "! Generated by fortsym. Do not edit."
    write (unit, "(a)") "! Generator: gen_rk54_cpu_tableau"
    write (unit, "(a)") "! Generator revision: "//revision()
    write (unit, "(a)") "! Regenerate with: cd tools/codegen && fo exec "// &
        "gen_rk54_cpu_tableau"
    write (unit, "(a)") "!"
    write (unit, "(a)") "! Cash, Karp, ACM TOMS 16(3), 201-222 (1990). The"
    write (unit, "(a)") "! order conditions were checked in exact arithmetic"
    write (unit, "(a)") "! before these values were rounded: the rows sum to"
    write (unit, "(a)") "! their nodes, the weights attain order 5, and the"
    write (unit, "(a)") "! embedded weights attain order 4 and not 5."
    write (unit, "(a)") ""
    write (unit, "(a)") "module fortnum_rk54_ck_tableau"
    write (unit, "(a)") "    use, intrinsic :: iso_fortran_env, only: dp => real64"
    write (unit, "(a)") "    implicit none"
    write (unit, "(a)") "    private"
    write (unit, "(a)") ""
    do i = 1, size(names)
        write (unit, "(a)") "    public :: "//chars(names(i))
    end do
    write (unit, "(a)") ""
    do i = 1, size(names)
        write (unit, "(a)") "    real(dp), parameter :: "//chars(names(i))// &
            " = "//chars(values(i))
    end do
    write (unit, "(a)") ""
    write (unit, "(a)") "end module fortnum_rk54_ck_tableau"
    close (unit)
    call codegen_log("wrote "//path)

contains

    subroutine collect(name, exact_value)
        character(*), intent(in) :: name, exact_value
        real(dp) :: value
        logical :: converted
        character(len=40) :: text

        value = exact_to_real(exact_value, converted)
        if (.not. converted) error stop name//": not an exact rational"
        ! 17 significant digits round-trip an IEEE double exactly, so the
        ! emitted text names one specific double and not a nearby one. The
        ! field has to hold sign, digit, point, 17 digits, E, exponent sign and
        ! three exponent digits: 25 characters for a negative value.
        write (text, "(es26.17e3)") value
        names = [names, str(name)]
        values = [values, str(trim(adjustl(text))//"_dp")]
    end subroutine collect

    subroutine build_cash_karp(t)
        type(butcher_t), intent(out) :: t
        logical :: built

        call rk_from_rows(6, &
            [character(len=16) :: &
             "1/5", &
             "3/40", "9/40", &
             "3/10", "-9/10", "6/5", &
             "-11/54", "5/2", "-70/27", "35/27", &
             "1631/55296", "175/512", "575/13824", "44275/110592", &
             "253/4096"], &
            [character(len=16) :: "37/378", "0", "250/621", "125/594", "0", &
             "512/1771"], &
            [character(len=16) :: "0", "1/5", "3/10", "3/5", "1", "7/8"], &
            t, built, &
            bhat=[character(len=16) :: "2825/27648", "0", "18575/48384", &
                  "13525/55296", "277/14336", "1/4"])
        if (.not. built) error stop "Cash-Karp tableau is not exact rational data"
    end subroutine build_cash_karp

    subroutine verify(t)
        type(butcher_t), intent(in) :: t

        if (.not. rk_is_consistent(t)) then
            error stop "Cash-Karp: stage rows do not sum to their nodes"
        end if
        if (.not. rk_attains_order(t, t%b, 5)) then
            error stop "Cash-Karp: weights do not attain order 5"
        end if
        if (.not. rk_attains_order(t, t%bhat, 4)) then
            error stop "Cash-Karp: embedded weights do not attain order 4"
        end if
        if (rk_attains_order(t, t%bhat, 5)) then
            error stop "Cash-Karp: embedded weights match the main order"
        end if
        if (rk_is_fsal(t)) error stop "Cash-Karp: unexpectedly FSAL"
        call codegen_log("Cash-Karp: consistent, order 5(4) verified")
    end subroutine verify

    pure function digits(value) result(text)
        integer, intent(in) :: value
        character(:), allocatable :: text
        character(len=12) :: buffer

        write (buffer, "(i0)") value
        text = trim(buffer)
    end function digits

    function revision() result(text)
        character(:), allocatable :: text
        character(128) :: line
        integer :: u, stat

        open (newunit=u, file="fortsym-rk54.lock", status="old", &
              action="read", iostat=stat)
        if (stat /= 0) error stop "cannot read fortsym-rk54.lock"
        read (u, "(a)", iostat=stat) line
        close (u)
        if (stat /= 0) error stop "cannot parse fortsym-rk54.lock"
        text = "fortsym@"//trim(line)
    end function revision

end program gen_rk54_cpu_tableau
