module fortnum_sobol
    ! Sobol low-discrepancy sequence with caller-owned explicit state.
    !
    ! A Sobol sequence fills the unit cube far more evenly than independent
    ! uniform draws: its star discrepancy falls like (log N)^d / N rather than
    ! the 1/sqrt(N) of pseudorandom points. That is why quasi-Monte Carlo
    ! integration and design-of-experiments initialization use it, and why
    ! Bayesian optimization seeds its first batch with it instead of with
    ! random points that clump and leave holes.
    !
    ! Construction (Sobol 1967; Bratley & Fox, TOMS 1988; Joe & Kuo, TOMS 2003).
    ! Each dimension owns a set of 32 direction numbers v_k derived from a
    ! primitive polynomial over GF(2) and a set of odd initial values m_k:
    !
    !     m_k = 2 a_1 m_{k-1} XOR 4 a_2 m_{k-2} XOR ... XOR 2^s m_{k-s} XOR m_{k-s}
    !     v_k = m_k * 2^(32-k)
    !
    ! Points are generated by the Gray-code recurrence of Antonov & Saleev
    ! (1979): consecutive points differ in exactly one direction number,
    !
    !     x_i = x_{i-1} XOR v_c,   c = position of the rightmost zero bit of i-1
    !
    ! which costs one exclusive-or per dimension per point and visits the same
    ! set of points as the direct construction, in a different order.
    !
    ! State is explicit and caller-owned, following the same rule as
    ! fortnum_rng: no module-level mutable state, so two threads holding
    ! separate sobol_t never race and a sequence is reproducible from its index
    ! alone.
    !
    ! Derivative policy: primal_only. A quasi-random point is not a
    ! differentiable function of its index; the index is an inactive argument.
    !
    ! Fortran has no unsigned integer, so direction numbers and the running
    ! state are held in int64 and masked to 32 bits. That keeps every
    ! intermediate positive and the shifts well defined.

    use, intrinsic :: iso_fortran_env, only: dp => real64, int64
    use fortnum_status, only: fortnum_status_t, status_set, &
        FORTNUM_OK, FORTNUM_DOMAIN_ERROR, FORTNUM_NOT_IMPLEMENTED
    implicit none
    private

    public :: sobol_t
    public :: sobol_initialize
    public :: sobol_next
    public :: sobol_skip
    public :: sobol_fill
    public :: SOBOL_MAX_DIMENSION

    ! Bits of resolution. 2^32 distinct values per coordinate.
    integer, parameter :: SOBOL_BITS = 32
    integer(int64), parameter :: TWO_POW_32 = 4294967296_int64
    integer(int64), parameter :: MASK_32 = TWO_POW_32 - 1_int64

    ! Direction-number data is tabulated for this many dimensions. Beyond it the
    ! initializer refuses rather than falling back to a different generator,
    ! because a silent fallback would destroy the very property the caller asked
    ! for and would not be visible in the output.
    integer, parameter :: SOBOL_MAX_DIMENSION = 21

    ! Degree of the primitive polynomial for dimensions 2..SOBOL_MAX_DIMENSION.
    integer, parameter :: POLY_DEGREE(2:SOBOL_MAX_DIMENSION) = [ &
        1, 2, 3, 3, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7]

    ! Polynomial coefficients a_1..a_{s-1} packed as an integer, one per
    ! dimension (Joe & Kuo, new-joe-kuo-6.21201).
    integer, parameter :: POLY_COEFFICIENT(2:SOBOL_MAX_DIMENSION) = [ &
        0, 1, 1, 2, 1, 4, 2, 4, 7, 11, 13, 14, 1, 13, 16, 19, 22, 25, 1, 4]

    ! Initial direction integers m_1..m_s, padded with zeros to width 7.
    integer, parameter :: INITIAL_M(7, 2:SOBOL_MAX_DIMENSION) = reshape([ &
        1, 0, 0, 0, 0, 0, 0, &
        1, 3, 0, 0, 0, 0, 0, &
        1, 3, 1, 0, 0, 0, 0, &
        1, 1, 1, 0, 0, 0, 0, &
        1, 1, 3, 3, 0, 0, 0, &
        1, 3, 5, 13, 0, 0, 0, &
        1, 1, 5, 5, 17, 0, 0, &
        1, 1, 5, 5, 5, 0, 0, &
        1, 1, 7, 11, 19, 0, 0, &
        1, 1, 5, 1, 1, 0, 0, &
        1, 1, 1, 3, 11, 0, 0, &
        1, 3, 5, 5, 31, 0, 0, &
        1, 3, 3, 9, 7, 49, 0, &
        1, 1, 1, 15, 21, 21, 0, &
        1, 3, 1, 13, 27, 49, 0, &
        1, 1, 1, 15, 7, 5, 0, &
        1, 3, 1, 15, 13, 25, 0, &
        1, 1, 5, 5, 19, 61, 0, &
        1, 3, 7, 11, 23, 15, 103, &
        1, 3, 7, 13, 13, 15, 69], [7, SOBOL_MAX_DIMENSION - 1])

    ! Caller-owned generator state. `index` counts points already emitted, so
    ! the state is fully described by (dimension, index) plus the fixed table.
    type :: sobol_t
        integer :: dimension = 0
        integer(int64) :: index = 0_int64
        integer(int64), allocatable :: direction(:, :)
        integer(int64), allocatable :: current(:)
    end type sobol_t

contains

    ! Build the direction numbers for `dimension` coordinates.
    subroutine sobol_initialize(sequence, dimension, status)
        type(sobol_t), intent(out) :: sequence
        integer, intent(in) :: dimension
        type(fortnum_status_t), intent(out) :: status
        integer(int64) :: m(SOBOL_BITS), value, term
        integer :: j, k, degree, coefficient, bit

        if (dimension < 1) then
            call status_set(status, FORTNUM_DOMAIN_ERROR, &
                "sobol: dimension must be positive")
            return
        end if
        if (dimension > SOBOL_MAX_DIMENSION) then
            call status_set(status, FORTNUM_NOT_IMPLEMENTED, &
                "sobol: tabulated direction numbers stop at dimension 21")
            return
        end if

        sequence%dimension = dimension
        sequence%index = 0_int64
        allocate (sequence%direction(dimension, SOBOL_BITS))
        allocate (sequence%current(dimension))
        sequence%current = 0_int64

        ! First dimension: every m_k is one, so v_k is a single walking bit and
        ! the coordinate is the radical-inverse (van der Corput) sequence.
        do k = 1, SOBOL_BITS
            sequence%direction(1, k) = ishft(1_int64, SOBOL_BITS - k)
        end do

        do j = 2, dimension
            degree = POLY_DEGREE(j)
            coefficient = POLY_COEFFICIENT(j)
            m = 0_int64
            do k = 1, degree
                m(k) = int(INITIAL_M(k, j), int64)
            end do
            do k = degree + 1, SOBOL_BITS
                ! m_k = 2^s m_{k-s} XOR m_{k-s} XOR (sum over set coefficient
                ! bits of 2^i m_{k-i}), all sums being exclusive-or over GF(2).
                value = ieor(ishft(m(k - degree), degree), m(k - degree))
                do bit = 1, degree - 1
                    if (btest(coefficient, degree - 1 - bit)) then
                        term = ishft(m(k - bit), bit)
                        value = ieor(value, term)
                    end if
                end do
                m(k) = iand(value, MASK_32)
            end do
            do k = 1, SOBOL_BITS
                sequence%direction(j, k) = iand(ishft(m(k), SOBOL_BITS - k), MASK_32)
            end do
        end do
        call status_set(status, FORTNUM_OK, "")
    end subroutine sobol_initialize

    ! Emit the next point, each coordinate in [0, 1).
    !
    ! The first point of the Gray-code sequence is the origin. That is a genuine
    ! member of the sequence, not a defect, but a caller using the points as
    ! design sites usually wants to skip it; `sobol_skip` exists for that.
    subroutine sobol_next(sequence, point, status)
        type(sobol_t), intent(inout) :: sequence
        real(dp), intent(out) :: point(:)
        type(fortnum_status_t), intent(out) :: status
        integer :: column, j

        if (sequence%dimension == 0) then
            call status_set(status, FORTNUM_DOMAIN_ERROR, &
                "sobol: sequence is not initialized")
            return
        end if
        if (size(point) /= sequence%dimension) then
            call status_set(status, FORTNUM_DOMAIN_ERROR, &
                "sobol: point width does not match the sequence dimension")
            return
        end if
        if (sequence%index >= TWO_POW_32) then
            call status_set(status, FORTNUM_DOMAIN_ERROR, &
                "sobol: sequence exhausted at 2^32 points")
            return
        end if

        do j = 1, sequence%dimension
            point(j) = real(sequence%current(j), dp)/real(TWO_POW_32, dp)
        end do

        column = rightmost_zero_bit(sequence%index)
        do j = 1, sequence%dimension
            sequence%current(j) = ieor(sequence%current(j), &
                sequence%direction(j, column))
        end do
        sequence%index = sequence%index + 1_int64
    end subroutine sobol_next

    ! Advance by `count` points without materializing them.
    subroutine sobol_skip(sequence, count, status)
        type(sobol_t), intent(inout) :: sequence
        integer(int64), intent(in) :: count
        type(fortnum_status_t), intent(out) :: status
        real(dp), allocatable :: scratch(:)
        integer(int64) :: k

        if (count < 0_int64) then
            call status_set(status, FORTNUM_DOMAIN_ERROR, &
                "sobol: cannot skip a negative count")
            return
        end if
        if (sequence%dimension == 0) then
            call status_set(status, FORTNUM_DOMAIN_ERROR, &
                "sobol: sequence is not initialized")
            return
        end if
        allocate (scratch(sequence%dimension))
        do k = 1_int64, count
            call sobol_next(sequence, scratch, status)
            if (status%code /= FORTNUM_OK) return
        end do
        call status_set(status, FORTNUM_OK, "")
    end subroutine sobol_skip

    ! Fill `points(n, dimension)` with the next n points, one per row.
    subroutine sobol_fill(sequence, points, status)
        type(sobol_t), intent(inout) :: sequence
        real(dp), intent(out) :: points(:, :)
        type(fortnum_status_t), intent(out) :: status
        integer :: i

        if (sequence%dimension == 0) then
            call status_set(status, FORTNUM_DOMAIN_ERROR, &
                "sobol: sequence is not initialized")
            return
        end if
        if (size(points, 2) /= sequence%dimension) then
            call status_set(status, FORTNUM_DOMAIN_ERROR, &
                "sobol: point width does not match the sequence dimension")
            return
        end if
        do i = 1, size(points, 1)
            call sobol_next(sequence, points(i, :), status)
            if (status%code /= FORTNUM_OK) return
        end do
        call status_set(status, FORTNUM_OK, "")
    end subroutine sobol_fill

    ! One-based position of the rightmost zero bit, which is the direction
    ! number the Gray-code step must flip.
    pure integer function rightmost_zero_bit(value) result(position)
        integer(int64), intent(in) :: value
        integer :: k

        position = SOBOL_BITS
        do k = 0, SOBOL_BITS - 1
            if (.not. btest(value, k)) then
                position = k + 1
                return
            end if
        end do
    end function rightmost_zero_bit

end module fortnum_sobol
