module fortnum_sobol
    ! Sobol low-discrepancy sequence with caller-owned explicit state.
    !
    ! A Sobol sequence fills the unit cube far more evenly than independent
    ! uniform draws: its star discrepancy falls like (log N)^d / N rather than
    ! the 1/sqrt(N) of pseudorandom points. That is why quasi-Monte Carlo
    ! integration and design-of-experiments initialization use it, and why
    ! Bayesian optimization seeds its first batch with it instead of with
    ! random points that clump and leave holes.
    !
    ! Construction (Sobol 1967; Bratley & Fox, TOMS 1988; Joe & Kuo, TOMS 2003).
    ! Each dimension owns a set of 32 direction numbers v_k derived from a
    ! primitive polynomial over GF(2) and a set of odd initial values m_k:
    !
    !     m_k = 2 a_1 m_{k-1} XOR 4 a_2 m_{k-2} XOR ... XOR 2^s m_{k-s} XOR m_{k-s}
    !     v_k = m_k * 2^(32-k)
    !
    ! Points are generated by the Gray-code recurrence of Antonov & Saleev
    ! (1979): consecutive points differ in exactly one direction number,
    !
    !     x_i = x_{i-1} XOR v_c,   c = position of the rightmost zero bit of i-1
    !
    ! which costs one exclusive-or per dimension per point and visits the same
    ! set of points as the direct construction, in a different order.
    !
    ! State is explicit and caller-owned, following the same rule as
    ! fortnum_rng: no module-level mutable state, so two threads holding
    ! separate sobol_t never race and a sequence is reproducible from its index
    ! alone.
    !
    ! Derivative policy: primal_only. A quasi-random point is not a
    ! differentiable function of its index; the index is an inactive argument.
    !
    ! Fortran has no unsigned integer, so direction numbers and the running
    ! state are held in int64 and masked to 32 bits. That keeps every
    ! intermediate positive and the shifts well defined.

    use, intrinsic :: iso_fortran_env, only: dp => real64, int64
    use fortnum_status, only: fortnum_status_t, status_set, &
        FORTNUM_OK, FORTNUM_DOMAIN_ERROR, FORTNUM_NOT_IMPLEMENTED
    implicit none
    private

    public :: sobol_t
    public :: sobol_initialize
    public :: sobol_next
    public :: sobol_skip
    public :: sobol_fill
    public :: sobol_primitive_polynomials
    public :: SOBOL_MAX_DIMENSION
    public :: SOBOL_TABULATED_DIMENSION

    ! Bits of resolution. 2^32 distinct values per coordinate.
    integer, parameter :: SOBOL_BITS = 32
    integer(int64), parameter :: TWO_POW_32 = 4294967296_int64
    integer(int64), parameter :: MASK_32 = TWO_POW_32 - 1_int64

    ! Highest dimension for which Joe-Kuo initial direction integers are
    ! tabulated. Beyond it the construction continues with computed primitive
    ! polynomials and unit initial values (see sobol_initialize), which is a
    ! valid Sobol sequence but not the Joe-Kuo optimized one.
    integer, parameter :: SOBOL_TABULATED_DIMENSION = 21

    ! Highest polynomial degree enumerated. Degree 13 yields 1110 primitive
    ! polynomials in total, so dimensions up to 1111 are constructible; the
    ! enumeration itself costs a few thousand cheap bit operations.
    integer, parameter :: MAX_POLY_DEGREE = 13
    integer, parameter :: SOBOL_MAX_DIMENSION = 1111

    ! Joe-Kuo initial direction integers m_1..m_s, padded with zeros to width 7.
    ! The primitive polynomials themselves are no longer tabulated: they are
    ! enumerated in canonical order by sobol_primitive_polynomials, which
    ! reproduces the published (degree, coefficient) sequence exactly and keeps
    ! going past where any table would stop.
    integer, parameter :: INITIAL_M(7, 2:SOBOL_TABULATED_DIMENSION) = reshape([ &
        1, 0, 0, 0, 0, 0, 0, &
        1, 3, 0, 0, 0, 0, 0, &
        1, 3, 1, 0, 0, 0, 0, &
        1, 1, 1, 0, 0, 0, 0, &
        1, 1, 3, 3, 0, 0, 0, &
        1, 3, 5, 13, 0, 0, 0, &
        1, 1, 5, 5, 17, 0, 0, &
        1, 1, 5, 5, 5, 0, 0, &
        1, 1, 7, 11, 19, 0, 0, &
        1, 1, 5, 1, 1, 0, 0, &
        1, 1, 1, 3, 11, 0, 0, &
        1, 3, 5, 5, 31, 0, 0, &
        1, 3, 3, 9, 7, 49, 0, &
        1, 1, 1, 15, 21, 21, 0, &
        1, 3, 1, 13, 27, 49, 0, &
        1, 1, 1, 15, 7, 5, 0, &
        1, 3, 1, 15, 13, 25, 0, &
        1, 1, 5, 5, 19, 61, 0, &
        1, 3, 7, 11, 23, 15, 103, &
        1, 3, 7, 13, 13, 15, 69], [7, SOBOL_TABULATED_DIMENSION - 1])

    ! Caller-owned generator state. `index` counts points already emitted, so
    ! the state is fully described by (dimension, index) plus the fixed table.
    type :: sobol_t
        integer :: dimension = 0
        integer(int64) :: index = 0_int64
        integer(int64), allocatable :: direction(:, :)
        integer(int64), allocatable :: current(:)
    end type sobol_t

contains

    ! Build the direction numbers for `dimension` coordinates.
    subroutine sobol_initialize(sequence, dimension, status)
        type(sobol_t), intent(out) :: sequence
        integer, intent(in) :: dimension
        type(fortnum_status_t), intent(out) :: status
        integer(int64) :: m(SOBOL_BITS), value, term
        integer, allocatable :: degrees(:), coefficients(:)
        integer :: j, k, degree, coefficient, bit, found

        if (dimension < 1) then
            call status_set(status, FORTNUM_DOMAIN_ERROR, &
                "sobol: dimension must be positive")
            return
        end if
        if (dimension > SOBOL_MAX_DIMENSION) then
            call status_set(status, FORTNUM_NOT_IMPLEMENTED, &
                "sobol: primitive polynomials are enumerated only to degree 13")
            return
        end if

        sequence%dimension = dimension
        sequence%index = 0_int64
        allocate (sequence%direction(dimension, SOBOL_BITS))
        allocate (sequence%current(dimension))
        sequence%current = 0_int64

        ! First dimension: every m_k is one, so v_k is a single walking bit and
        ! the coordinate is the radical-inverse (van der Corput) sequence.
        do k = 1, SOBOL_BITS
            sequence%direction(1, k) = ishft(1_int64, SOBOL_BITS - k)
        end do

        ! One primitive polynomial per dimension after the first, in canonical
        ! order. Dimensions 2..21 additionally use the published Joe-Kuo
        ! initial values, which are chosen for good low-dimensional
        ! projections; beyond the table the initial values are all one, which
        ! is admissible (each m_k must be odd and below 2^k) and still yields a
        ! valid Sobol sequence, just not the projection-optimized one.
        allocate (degrees(dimension), coefficients(dimension))
        call sobol_primitive_polynomials(dimension - 1, degrees, coefficients, found)
        if (found < dimension - 1) then
            call status_set(status, FORTNUM_NOT_IMPLEMENTED, &
                "sobol: not enough primitive polynomials for this dimension")
            return
        end if

        do j = 2, dimension
            degree = degrees(j - 1)
            coefficient = coefficients(j - 1)
            m = 0_int64
            do k = 1, degree
                if (j <= SOBOL_TABULATED_DIMENSION) then
                    m(k) = int(INITIAL_M(k, j), int64)
                else
                    m(k) = 1_int64
                end if
            end do
            do k = degree + 1, SOBOL_BITS
                ! m_k = 2^s m_{k-s} XOR m_{k-s} XOR (sum over set coefficient
                ! bits of 2^i m_{k-i}), all sums being exclusive-or over GF(2).
                value = ieor(ishft(m(k - degree), degree), m(k - degree))
                do bit = 1, degree - 1
                    if (btest(coefficient, degree - 1 - bit)) then
                        term = ishft(m(k - bit), bit)
                        value = ieor(value, term)
                    end if
                end do
                m(k) = iand(value, MASK_32)
            end do
            do k = 1, SOBOL_BITS
                sequence%direction(j, k) = iand(ishft(m(k), SOBOL_BITS - k), MASK_32)
            end do
        end do
        call status_set(status, FORTNUM_OK, "")
    end subroutine sobol_initialize

    ! Emit the next point, each coordinate in [0, 1).
    !
    ! The first point of the Gray-code sequence is the origin. That is a genuine
    ! member of the sequence, not a defect, but a caller using the points as
    ! design sites usually wants to skip it; `sobol_skip` exists for that.
    subroutine sobol_next(sequence, point, status)
        type(sobol_t), intent(inout) :: sequence
        real(dp), intent(out) :: point(:)
        type(fortnum_status_t), intent(out) :: status
        integer :: column, j

        if (sequence%dimension == 0) then
            call status_set(status, FORTNUM_DOMAIN_ERROR, &
                "sobol: sequence is not initialized")
            return
        end if
        if (size(point) /= sequence%dimension) then
            call status_set(status, FORTNUM_DOMAIN_ERROR, &
                "sobol: point width does not match the sequence dimension")
            return
        end if
        if (sequence%index >= TWO_POW_32) then
            call status_set(status, FORTNUM_DOMAIN_ERROR, &
                "sobol: sequence exhausted at 2^32 points")
            return
        end if

        do j = 1, sequence%dimension
            point(j) = real(sequence%current(j), dp)/real(TWO_POW_32, dp)
        end do

        column = rightmost_zero_bit(sequence%index)
        do j = 1, sequence%dimension
            sequence%current(j) = ieor(sequence%current(j), &
                sequence%direction(j, column))
        end do
        sequence%index = sequence%index + 1_int64
    end subroutine sobol_next

    ! Advance by `count` points without materializing them.
    subroutine sobol_skip(sequence, count, status)
        type(sobol_t), intent(inout) :: sequence
        integer(int64), intent(in) :: count
        type(fortnum_status_t), intent(out) :: status
        real(dp), allocatable :: scratch(:)
        integer(int64) :: k

        if (count < 0_int64) then
            call status_set(status, FORTNUM_DOMAIN_ERROR, &
                "sobol: cannot skip a negative count")
            return
        end if
        if (sequence%dimension == 0) then
            call status_set(status, FORTNUM_DOMAIN_ERROR, &
                "sobol: sequence is not initialized")
            return
        end if
        allocate (scratch(sequence%dimension))
        do k = 1_int64, count
            call sobol_next(sequence, scratch, status)
            if (status%code /= FORTNUM_OK) return
        end do
        call status_set(status, FORTNUM_OK, "")
    end subroutine sobol_skip

    ! Fill `points(n, dimension)` with the next n points, one per row.
    subroutine sobol_fill(sequence, points, status)
        type(sobol_t), intent(inout) :: sequence
        real(dp), intent(out) :: points(:, :)
        type(fortnum_status_t), intent(out) :: status
        integer :: i

        if (sequence%dimension == 0) then
            call status_set(status, FORTNUM_DOMAIN_ERROR, &
                "sobol: sequence is not initialized")
            return
        end if
        if (size(points, 2) /= sequence%dimension) then
            call status_set(status, FORTNUM_DOMAIN_ERROR, &
                "sobol: point width does not match the sequence dimension")
            return
        end if
        do i = 1, size(points, 1)
            call sobol_next(sequence, points(i, :), status)
            if (status%code /= FORTNUM_OK) return
        end do
        call status_set(status, FORTNUM_OK, "")
    end subroutine sobol_fill


    ! Enumerate primitive polynomials over GF(2) in canonical order: increasing
    ! degree, and within a degree increasing coefficient word.
    !
    ! A Sobol dimension needs a primitive polynomial because primitivity is
    ! exactly the condition that makes the direction-number recurrence visit
    ! every nonzero residue before repeating. An irreducible-but-not-primitive
    ! polynomial produces a short cycle and a coordinate that silently stops
    ! being equidistributed partway through the sequence.
    !
    ! The polynomial is x^s + a_1 x^(s-1) + ... + a_(s-1) x + 1, stored as the
    ! coefficient word a_1..a_(s-1). The leading and constant terms are implicit:
    ! a primitive polynomial always has a nonzero constant term.
    subroutine sobol_primitive_polynomials(wanted, degrees, coefficients, found)
        integer, intent(in) :: wanted
        integer, intent(out) :: degrees(:)
        integer, intent(out) :: coefficients(:)
        integer, intent(out) :: found
        integer :: degree, coefficient, limit

        found = 0
        degrees = 0
        coefficients = 0
        if (wanted < 1) return

        do degree = 1, MAX_POLY_DEGREE
            limit = 2**max(degree - 1, 0) - 1
            do coefficient = 0, limit
                if (.not. is_primitive(degree, coefficient)) cycle
                found = found + 1
                if (found > size(degrees) .or. found > size(coefficients)) then
                    found = found - 1
                    return
                end if
                degrees(found) = degree
                coefficients(found) = coefficient
                if (found >= wanted) return
            end do
        end do
    end subroutine sobol_primitive_polynomials

    ! True when x has multiplicative order exactly 2^degree - 1 modulo the
    ! polynomial, which is the definition of primitivity.
    logical function is_primitive(degree, coefficient) result(primitive)
        integer, intent(in) :: degree, coefficient
        integer(int64) :: polynomial, order, quotient, residue
        integer :: factors(16), n_factors, k

        primitive = .false.
        if (degree < 1) return
        if (degree == 1) then
            ! x + 1 is the only degree-one candidate and is primitive.
            primitive = coefficient == 0
            return
        end if

        polynomial = ior(ior(ishft(1_int64, degree), &
            ishft(int(coefficient, int64), 1)), 1_int64)
        order = ishft(1_int64, degree) - 1_int64

        ! x^order must be the identity.
        if (gf2_power(2_int64, order, polynomial, degree) /= 1_int64) return

        ! and no proper divisor of the order may already be the identity.
        call distinct_prime_factors(order, factors, n_factors)
        do k = 1, n_factors
            quotient = order/int(factors(k), int64)
            residue = gf2_power(2_int64, quotient, polynomial, degree)
            if (residue == 1_int64) return
        end do
        primitive = .true.
    end function is_primitive

    ! Carry-less multiply modulo the polynomial, over GF(2).
    pure function gf2_multiply(a, b, polynomial, degree) result(product)
        integer(int64), intent(in) :: a, b, polynomial
        integer, intent(in) :: degree
        integer(int64) :: product, shifted
        integer :: k

        product = 0_int64
        shifted = a
        do k = 0, degree - 1
            if (btest(b, k)) product = ieor(product, shifted)
            shifted = ishft(shifted, 1)
            if (btest(shifted, degree)) shifted = ieor(shifted, polynomial)
        end do
    end function gf2_multiply

    pure function gf2_power(base, exponent, polynomial, degree) result(value)
        integer(int64), intent(in) :: base, exponent, polynomial
        integer, intent(in) :: degree
        integer(int64) :: value, factor, remaining

        value = 1_int64
        factor = base
        remaining = exponent
        do while (remaining > 0_int64)
            if (btest(remaining, 0)) &
                value = gf2_multiply(value, factor, polynomial, degree)
            factor = gf2_multiply(factor, factor, polynomial, degree)
            remaining = ishft(remaining, -1)
        end do
    end function gf2_power

    ! Trial division. The largest order tested is 2^13 - 1 = 8191, so this is
    ! trivial work done once at initialization.
    pure subroutine distinct_prime_factors(value, factors, count)
        integer(int64), intent(in) :: value
        integer, intent(out) :: factors(:)
        integer, intent(out) :: count
        integer(int64) :: remaining, divisor

        count = 0
        factors = 0
        remaining = value
        divisor = 2_int64
        do while (divisor*divisor <= remaining)
            if (mod(remaining, divisor) == 0_int64) then
                count = count + 1
                if (count <= size(factors)) factors(count) = int(divisor)
                do while (mod(remaining, divisor) == 0_int64)
                    remaining = remaining/divisor
                end do
            end if
            divisor = divisor + 1_int64
        end do
        if (remaining > 1_int64) then
            count = count + 1
            if (count <= size(factors)) factors(count) = int(remaining)
        end if
    end subroutine distinct_prime_factors

    ! One-based position of the rightmost zero bit, which is the direction
    ! number the Gray-code step must flip.
    pure integer function rightmost_zero_bit(value) result(position)
        integer(int64), intent(in) :: value
        integer :: k

        position = SOBOL_BITS
        do k = 0, SOBOL_BITS - 1
            if (.not. btest(value, k)) then
                position = k + 1
                return
            end if
        end do
    end function rightmost_zero_bit

end module fortnum_sobol
