module fortnum_ad_backend
    !! Which engine's derivative kernels the library calls.
    !!
    !! fortnum carries two sets of generated derivatives for the same
    !! operators. The fortsym set is symbolic: for a small closed-form operator
    !! it can beat anything a differentiator produces, because it simplifies
    !! the expression rather than the program. The fortad set is
    !! source-transformation, which is what scales to operators with loops and
    !! branches where a symbolic form would blow up.
    !!
    !! Both are kept compiled and both are tested against each other, so
    !! switching is a one-line change here rather than a port. The selector is
    !! a named constant, so the compiler folds the branch and the unused call
    !! costs nothing at runtime.
    implicit none
    private

    public :: FORTNUM_AD_FORTSYM, FORTNUM_AD_FORTAD, FORTNUM_AD_ENGINE

    !! Symbolic kernels generated by fortsym.
    integer, parameter :: FORTNUM_AD_FORTSYM = 1
    !! Source-transformation kernels generated by fortad.
    integer, parameter :: FORTNUM_AD_FORTAD = 2

    !! The engine in use. fortad is the default: it covers every operator
    !! Enzyme covers, needs no external toolchain, and builds with gfortran.
    integer, parameter :: FORTNUM_AD_ENGINE = FORTNUM_AD_FORTAD

end module fortnum_ad_backend
