# FortnumAddEnzymeTest.cmake -- register one Enzyme derivative-check test.
#
# fortnum_add_enzyme_test(
#     NAME      <test_name>
#     SOURCES   <f90> [<f90> ...]   # last source holds the program; earlier
#                                   # sources are kernel modules compiled first
#     MODE      forward | reverse   # documents which __enzyme_* entry the
#                                   # wrapper exercises (informational)
#     OPT_LEVEL O0 | O2)            # optimization for IR emission and link
#
# Pipeline per test (proven against flang/LLVM/Enzyme 22):
#   1. flang-new -O<lvl> -S -emit-llvm <src> -o <src>.ll   (one IR per source)
#   2. llvm-link the IRs into one module                    (skipped if single)
#   3. opt -load-pass-plugin=<plugin> -passes=enzyme <ll> -o <ll.e>
#   4. flang-new -O<lvl> <ll.e> -o <exe>                    (link Fortran rt)
# The built program asserts its derivative against the analytic value and
# exits nonzero on mismatch, so add_test alone is the pass/fail oracle.
#
# When FORTNUM_ENZYME_AVAILABLE is FALSE the test is still registered, but as
# a command that reports SKIP and a ctest SKIP_RETURN_CODE, so the suite stays
# green on a machine without the Enzyme plugin.
#
# Requires FortnumEnzyme.cmake to have run (defines the result variables).

include_guard(GLOBAL)

function(fortnum_add_enzyme_test)
    set(_opts "")
    set(_one NAME MODE OPT_LEVEL)
    set(_multi SOURCES)
    cmake_parse_arguments(FAET "${_opts}" "${_one}" "${_multi}" ${ARGN})

    if(NOT FAET_NAME)
        message(FATAL_ERROR "fortnum_add_enzyme_test: NAME is required")
    endif()
    if(NOT FAET_SOURCES)
        message(FATAL_ERROR "fortnum_add_enzyme_test(${FAET_NAME}): SOURCES required")
    endif()
    if(NOT FAET_MODE)
        set(FAET_MODE "reverse")
    endif()
    if(NOT FAET_OPT_LEVEL)
        set(FAET_OPT_LEVEL "O2")
    endif()

    # Absolute source paths for the build script.
    set(_abs_sources "")
    foreach(_s IN LISTS FAET_SOURCES)
        if(IS_ABSOLUTE "${_s}")
            list(APPEND _abs_sources "${_s}")
        else()
            list(APPEND _abs_sources "${CMAKE_CURRENT_SOURCE_DIR}/${_s}")
        endif()
    endforeach()

    if(NOT FORTNUM_ENZYME_AVAILABLE)
        # Register a skip so ctest shows the test as Skipped, not missing.
        add_test(NAME ${FAET_NAME}
            COMMAND ${CMAKE_COMMAND} -E echo
                "SKIP ${FAET_NAME}: Enzyme plugin unavailable (see docs/design/enzyme_toolchain.md)")
        set_tests_properties(${FAET_NAME} PROPERTIES
            SKIP_REGULAR_EXPRESSION "^SKIP ")
        return()
    endif()

    set(_workdir "${CMAKE_CURRENT_BINARY_DIR}/${FAET_NAME}.enzyme")
    set(_exe "${_workdir}/${FAET_NAME}")

    # Emit a per-test CMake -P driver that runs the four-stage pipeline. Doing
    # it in script mode keeps the staged flang/opt/flang calls portable and
    # lets ctest treat any stage failure as a hard test failure.
    set(_driver "${_workdir}/run_pipeline.cmake")
    file(MAKE_DIRECTORY "${_workdir}")

    string(REPLACE ";" "|" _sources_packed "${_abs_sources}")

    file(WRITE "${_driver}" "\
# Generated by fortnum_add_enzyme_test(${FAET_NAME}). Do not edit.
set(FLANG \"${FORTNUM_FLANG_EXECUTABLE}\")
set(OPT \"${FORTNUM_LLVM_OPT_EXECUTABLE}\")
set(PLUGIN \"${FORTNUM_ENZYME_PLUGIN}\")
set(OPTLVL \"-${FAET_OPT_LEVEL}\")
set(WORK \"${_workdir}\")
set(EXE \"${_exe}\")
string(REPLACE \"|\" \";\" SOURCES \"${_sources_packed}\")

function(_run)
    execute_process(COMMAND \${ARGN} RESULT_VARIABLE _rc)
    if(NOT _rc EQUAL 0)
        message(FATAL_ERROR \"command failed (rc=\${_rc}): \${ARGN}\")
    endif()
endfunction()

set(_lls \"\")
set(_i 0)
foreach(_src IN LISTS SOURCES)
    set(_ll \"\${WORK}/stage_\${_i}.ll\")
    _run(\${FLANG} \${OPTLVL} -S -emit-llvm \${_src} -o \${_ll})
    list(APPEND _lls \${_ll})
    math(EXPR _i \"\${_i}+1\")
endforeach()

list(LENGTH _lls _n)
if(_n GREATER 1)
    # llvm-link sits next to opt; derive its path.
    get_filename_component(_optdir \${OPT} DIRECTORY)
    find_program(LLVM_LINK NAMES llvm-link HINTS \${_optdir})
    if(NOT LLVM_LINK)
        message(FATAL_ERROR \"llvm-link not found next to opt at \${_optdir}\")
    endif()
    set(_linked \"\${WORK}/linked.ll\")
    _run(\${LLVM_LINK} -S \${_lls} -o \${_linked})
else()
    set(_linked \${_lls})
endif()

set(_enz \"\${WORK}/enzyme.ll\")
_run(\${OPT} -load-pass-plugin=\${PLUGIN} -passes=enzyme \${_linked} -S -o \${_enz})
_run(\${FLANG} \${OPTLVL} \${_enz} -o \${EXE})
")

    add_custom_command(
        OUTPUT "${_exe}"
        COMMAND ${CMAKE_COMMAND} -P "${_driver}"
        DEPENDS ${_abs_sources} "${_driver}"
        WORKING_DIRECTORY "${_workdir}"
        COMMENT "Building Enzyme test ${FAET_NAME} (${FAET_MODE}, ${FAET_OPT_LEVEL})"
        VERBATIM)

    add_custom_target(${FAET_NAME}_build ALL DEPENDS "${_exe}")

    add_test(NAME ${FAET_NAME} COMMAND "${_exe}")
endfunction()
