# FortnumAddEnzymeTest.cmake -- register one Enzyme derivative-check test.
#
# fortnum_add_enzyme_test(
#     NAME      <test_name>
#     SOURCES   <f90> [<f90> ...]   # last source holds the program; earlier
#                                   # sources are kernel modules compiled first
#     MODE      forward | reverse   # documents which __enzyme_* entry the
#                                   # wrapper exercises (informational)
#     OPT_LEVEL O0 | O2)            # optimization for IR emission and link
#
# Pipeline per test (proven against flang/LLVM/Enzyme 22):
#   1. flang-new -O<lvl> -S -emit-llvm <src> -o <src>.ll   (one IR per source)
#   2. llvm-link the IRs into one module                    (skipped if single)
#   3. opt -load-pass-plugin=<plugin> -passes=enzyme <ll> -o <ll.e>
#   4. flang-new -O<lvl> <ll.e> -o <exe>                    (link Fortran rt)
# The built program asserts its derivative against the analytic value and
# exits nonzero on mismatch, so add_test alone is the pass/fail oracle.
#
# When FORTNUM_ENZYME_AVAILABLE is FALSE the test is still registered, but as
# a command that reports SKIP and a ctest SKIP_RETURN_CODE, so the suite stays
# green on a machine without the Enzyme plugin.
#
# Requires FortnumEnzyme.cmake to have run (defines the result variables).

include_guard(GLOBAL)

function(fortnum_add_enzyme_test)
    set(_opts "")
    set(_one NAME MODE OPT_LEVEL)
    set(_multi SOURCES FORWARD_RULES LINK_LIBRARIES)
    cmake_parse_arguments(FAET "${_opts}" "${_one}" "${_multi}" ${ARGN})

    if(NOT FAET_NAME)
        message(FATAL_ERROR "fortnum_add_enzyme_test: NAME is required")
    endif()
    if(NOT FAET_SOURCES)
        message(FATAL_ERROR "fortnum_add_enzyme_test(${FAET_NAME}): SOURCES required")
    endif()
    if(NOT FAET_MODE)
        set(FAET_MODE "reverse")
    endif()
    if(NOT FAET_OPT_LEVEL)
        set(FAET_OPT_LEVEL "O2")
    endif()

    # Absolute source paths for the build script.
    set(_abs_sources "")
    foreach(_s IN LISTS FAET_SOURCES)
        if(IS_ABSOLUTE "${_s}")
            list(APPEND _abs_sources "${_s}")
        else()
            list(APPEND _abs_sources "${CMAKE_CURRENT_SOURCE_DIR}/${_s}")
        endif()
    endforeach()

    if(NOT FORTNUM_ENZYME_AVAILABLE)
        # Register a skip so ctest shows the test as Skipped, not missing.
        add_test(NAME ${FAET_NAME}
            COMMAND ${CMAKE_COMMAND} -E echo
                "SKIP ${FAET_NAME}: Enzyme plugin unavailable (see docs/design/enzyme_toolchain.md)")
        set_tests_properties(${FAET_NAME} PROPERTIES
            SKIP_REGULAR_EXPRESSION "^SKIP ")
        return()
    endif()

    set(_workdir "${CMAKE_CURRENT_BINARY_DIR}/${FAET_NAME}.enzyme")
    set(_exe "${_workdir}/${FAET_NAME}")

    # Emit a per-test CMake -P driver that runs the four-stage pipeline. Doing
    # it in script mode keeps the staged flang/opt/flang calls portable and
    # lets ctest treat any stage failure as a hard test failure.
    set(_driver "${_workdir}/run_pipeline.cmake")
    file(MAKE_DIRECTORY "${_workdir}")

    string(REPLACE ";" "|" _sources_packed "${_abs_sources}")
    string(REPLACE ";" "|" _forward_rules_packed "${FAET_FORWARD_RULES}")
    string(REPLACE ";" "|" _link_libraries_packed "${FAET_LINK_LIBRARIES}")

    file(WRITE "${_driver}" "\
# Generated by fortnum_add_enzyme_test(${FAET_NAME}). Do not edit.
set(FLANG \"${FORTNUM_FLANG_EXECUTABLE}\")
set(CLANG \"${FORTNUM_CLANG_EXECUTABLE}\")
set(OPT \"${FORTNUM_LLVM_OPT_EXECUTABLE}\")
set(PLUGIN \"${FORTNUM_ENZYME_PLUGIN}\")
set(OPTLVL \"-${FAET_OPT_LEVEL}\")
set(WORK \"${_workdir}\")
set(EXE \"${_exe}\")
string(REPLACE \"|\" \";\" SOURCES \"${_sources_packed}\")
string(REPLACE \"|\" \";\" FORWARD_RULES \"${_forward_rules_packed}\")
string(REPLACE \"|\" \";\" LINK_LIBRARIES \"${_link_libraries_packed}\")

function(_run)
    execute_process(COMMAND \${ARGN} RESULT_VARIABLE _rc)
    if(NOT _rc EQUAL 0)
        message(FATAL_ERROR \"command failed (rc=\${_rc}): \${ARGN}\")
    endif()
endfunction()

set(_lls \"\")
set(_i 0)
foreach(_src IN LISTS SOURCES)
    set(_ll \"\${WORK}/stage_\${_i}.ll\")
    get_filename_component(_ext \${_src} EXT)
    if(_ext STREQUAL \".c\")
        if(NOT CLANG)
            message(FATAL_ERROR \"clang is required for Enzyme C helper \${_src}\")
        endif()
        _run(\${CLANG} \${OPTLVL} -S -emit-llvm \${_src} -o \${_ll})
    else()
        _run(\${FLANG} \${OPTLVL} -S -emit-llvm \${_src} -o \${_ll})
    endif()
    list(APPEND _lls \${_ll})
    math(EXPR _i \"\${_i}+1\")
endforeach()

list(LENGTH _lls _n)
if(_n GREATER 1)
    # llvm-link sits next to opt; derive its path.
    get_filename_component(_optdir \${OPT} DIRECTORY)
    find_program(LLVM_LINK NAMES llvm-link HINTS \${_optdir})
    if(NOT LLVM_LINK)
        message(FATAL_ERROR \"llvm-link not found next to opt at \${_optdir}\")
    endif()
    set(_linked \"\${WORK}/linked.ll\")
    _run(\${LLVM_LINK} -S \${_lls} -o \${_linked})
else()
    set(_linked \${_lls})
endif()

# Attach custom forward rules to the primal definitions. Enzyme consumes
# function metadata; the C registration globals emitted by some front ends are
# not interpreted by the standalone LLVM pass.
if(FORWARD_RULES)
    file(READ \${_linked} _ir)
    set(_metadata_id 900000)
    foreach(_rule IN LISTS FORWARD_RULES)
        string(REPLACE \"=\" \";\" _parts \${_rule})
        list(LENGTH _parts _nparts)
        if(NOT _nparts EQUAL 2)
            message(FATAL_ERROR \"invalid FORWARD_RULE \${_rule}; expected primal=derivative\")
        endif()
        list(GET _parts 0 _primal)
        list(GET _parts 1 _derivative)
        string(REGEX MATCH \"define [^\\n]*@\${_primal}\\\\([^\\n]*\\\\)[^\\n]* \\\\{\" _definition \"\${_ir}\")
        if(NOT _definition)
            message(FATAL_ERROR \"custom-rule primal definition not found: \${_primal}\")
        endif()
        string(REGEX REPLACE \" \\\\{$\" \"\" _prefix \"\${_definition}\")
        set(_annotated \"\${_prefix} !enzyme_derivative !\${_metadata_id} {\")
        string(REPLACE \"\${_definition}\" \"\${_annotated}\" _ir \"\${_ir}\")
        string(APPEND _ir \"\\n!\${_metadata_id} = !{ptr @\${_derivative}}\\n\")
        math(EXPR _metadata_id \"\${_metadata_id}+1\")
    endforeach()
    set(_annotated_ir \"\${WORK}/annotated.ll\")
    file(WRITE \${_annotated_ir} \"\${_ir}\")
    set(_linked \${_annotated_ir})
endif()

set(_enz \"\${WORK}/enzyme.ll\")
_run(\${OPT} -load-pass-plugin=\${PLUGIN} -passes=enzyme \${_linked} -S -o \${_enz})
_run(\${FLANG} \${OPTLVL} \${_enz} -o \${EXE} \${LINK_LIBRARIES})
")

    add_custom_command(
        OUTPUT "${_exe}"
        COMMAND ${CMAKE_COMMAND} -P "${_driver}"
        DEPENDS ${_abs_sources} "${_driver}"
        WORKING_DIRECTORY "${_workdir}"
        COMMENT "Building Enzyme test ${FAET_NAME} (${FAET_MODE}, ${FAET_OPT_LEVEL})"
        VERBATIM)

    add_custom_target(${FAET_NAME}_build ALL DEPENDS "${_exe}")

    add_test(NAME ${FAET_NAME} COMMAND "${_exe}")
endfunction()
