function(fortnum_read_benchmark_selection record output_variable)
    if(NOT EXISTS "${record}")
        message(FATAL_ERROR "fortnum benchmark record not found: ${record}")
    endif()

    file(READ "${record}" record_json)
    string(JSON selected ERROR_VARIABLE json_error
        GET "${record_json}" selection selected)
    if(NOT json_error STREQUAL "NOTFOUND")
        message(FATAL_ERROR
            "invalid fortnum benchmark selection in ${record}: ${json_error}")
    endif()
    if(selected STREQUAL "")
        message(FATAL_ERROR "empty fortnum benchmark selection in ${record}")
    endif()

    set(${output_variable} "${selected}" PARENT_SCOPE)
endfunction()

function(fortnum_read_benchmark_entry record operator_variable product_variable
        workload_variable selected_variable)
    if(NOT EXISTS "${record}")
        message(FATAL_ERROR "fortnum benchmark record not found: ${record}")
    endif()
    file(READ "${record}" record_json)
    foreach(field IN ITEMS operator product workload)
        string(JSON value ERROR_VARIABLE json_error GET "${record_json}" ${field})
        if(NOT json_error STREQUAL "NOTFOUND")
            message(FATAL_ERROR
                "invalid '${field}' in fortnum benchmark record ${record}")
        endif()
        set(${field}_value "${value}")
    endforeach()
    string(JSON selected ERROR_VARIABLE json_error
        GET "${record_json}" selection selected)
    if(NOT json_error STREQUAL "NOTFOUND")
        message(FATAL_ERROR
            "invalid selection in fortnum benchmark record ${record}")
    endif()

    set(${operator_variable} "${operator_value}" PARENT_SCOPE)
    set(${product_variable} "${product_value}" PARENT_SCOPE)
    set(${workload_variable} "${workload_value}" PARENT_SCOPE)
    set(${selected_variable} "${selected}" PARENT_SCOPE)
endfunction()

function(fortnum_format_fortran_strings list_variable output_variable)
    list(LENGTH ${list_variable} count)
    math(EXPR last "${count} - 1")
    set(formatted "")
    foreach(index RANGE 0 ${last})
        list(GET ${list_variable} ${index} value)
        string(REPLACE "\"" "\"\"" value "${value}")
        if(index LESS last)
            string(APPEND formatted "        \"${value}\", &\n")
        else()
            string(APPEND formatted "        \"${value}\" &\n")
        endif()
    endforeach()
    set(${output_variable} "${formatted}" PARENT_SCOPE)
endfunction()
